#!/bin/bash
#set -x
script=../bin/gstat-validate-site
output=$(mktemp)

function test_ldif {
    echo -n "Testing ${ldif} ... " 
    ${script} -f $1 > ${output} 2>/dev/null
    if [ $? -eq 0 ]; then 
	echo "FAIL" 1>&2
	cat ${output}
	return
    fi
    if [ $(wc -l ${output} | sed 's/ .*//') -ne 2 ]; then
	echo "FAIL" 1>&2
	cat ${output}
	return
    fi
    grep "$2" ${output} >/dev/null 2>&1
    if [ $? -ne 0 ]; then 
	echo "FAIL" 1>&2
	cat ${output}
	return
    fi
    echo "OK"
}  

ldif=ldif/GlueSite/bad_email_syntax.ldif
message="Incorrect email address syntax."
test_ldif ${ldif} "${message}"

ldif=ldif/GlueSite/bad_email_root.ldif
message="Incorrect email address: mailto:root@cern.ch"
test_ldif ${ldif} "${message}"

ldif=ldif/GlueSite/bad_NGI.ldif
message="NGI_Rubish is not an official NGI"
test_ldif ${ldif} "${message}"

rm -f ${output}