dn: GlueSiteUniqueID=$SITE_NAME,mds-vo-name=resource,o=grid
objectClass: GlueTop
objectClass: GlueSite
objectClass: GlueKey
objectClass: GlueSchemaVersion
GlueSiteUniqueID: $SITE_NAME
GlueSiteName: $SITE_NAME
GlueSiteDescription: $SITE_DESC
GlueSiteUserSupportContact: mailto:$SITE_SUPPORT_EMAIL
GlueSiteSysAdminContact: mailto:$SITE_EMAIL
GlueSiteSecurityContact: mailto:$SITE_SECURITY_EMAIL
GlueSiteEmailContact: mailto:$SITE_EMAIL
GlueSiteLocation: $SITE_LOC
GlueSiteLatitude: $SITE_LAT
GlueSiteLongitude: $SITE_LON
GlueSiteWeb: $SITE_WEB
GlueSiteSponsor: none
GlueForeignKey: GlueSiteUniqueID=$SITE_NAME
GlueSchemaVersionMajor: 1
GlueSchemaVersionMinor: 3
GlueSiteOtherInfo: $OTHERINFO
