#
# List of site bdiis used by the dashboard scripts
#
# Note: List of WLCG sites updated from REBUS on 05.12.2013
#       List of LHCb sites updated from DIRAC on 06.12.2013
#
###############################################################


wlcg_site_bdiis = {
"Australia-ATLAS": "agsite.atlas.unimelb.edu.au",
"BEgrid-ULB-VUB": "sitebdii.iihe.ac.be",
"BEIJING-LCG2": "lcg002.ihep.ac.cn",
"BelGrid-UCL": "ingrid.cism.ucl.ac.be",
"BUDAPEST": "grid147.kfki.hu",
"CA-MCGILL-CLUMEQ-T2": "site-bdii.clumeq.mcgill.ca",
"CA-SCINET-T2": "lcg-se3.scinet.utoronto.ca",
"CA-VICTORIA-WESTGRID-T2": "charon02.westgrid.ca",
"CBPF": "site-bdii.cat.cbpf.br",
"CERN-PROD" : "prod-bdii.cern.ch",
"CIEMAT-LCG2": "lcg03.ciemat.es",
"CSCS-LCG2": "sbdii02.lcg.cscs.ch",
"CYFRONET-LCG2": "sbdii.grid.cyf-kr.edu.pl",
"DESY-HH": "grid-giis1.desy.de",
"DESY-ZN": "lcg-giis1.ifh.de",
"EELA-UNLP": "ce01.unlp.edu.ar",
"EELA-UTFSM": "site.hpc.utfsm.cl",
"EFDA-JET": "grid005.jet.efda.org",
"FI_HIP_T2": "bdii.hip.fi",
"FMPhI-UNIBA": "lcgbdii.dnp.fmph.uniba.sk",
"FZK-LCG2" : "giis-fzk.gridka.de",
"GoeGrid": "bdii.goegrid.gwdg.de",
"GR-07-UOI-HEPLAB": "grid03.physics.uoi.gr",
"GRIF": "grid14.lal.in2p3.fr",
"GSI-LCG2": "lcg-bdii.gsi.de",
"HEPHY-UIBK": "test-ui.uibk.ac.at",
"Hephy-Vienna": "bdii.oeaw.ac.at",
"ICM": "apel.grid.icm.edu.pl",
"IEPSAS-Kosice": "glmon-iep-grid.saske.sk",
"ifae": "sitebdii-ifae02.pic.es",
"IFCA-LCG2": "gridiis01.ifca.es",
"IFIC-LCG2": "bdii01.ific.uv.es",
"IL-TAU-HEP": "tau-bdii.hep.tau.ac.il",
"IN-DAE-VECC-02": "dcache-server.tier2-kol.res.in",
"IN2P3-CC": "cclcgip01.in2p3.fr",
"IN2P3-CC-T2": "cclcgip05.in2p3.fr",
"IN2P3-CPPM": "marbdii.in2p3.fr",
"IN2P3-IRES": "sbgbdii2.in2p3.fr",
"IN2P3-LAPP": "lapp-site01.in2p3.fr",
"IN2P3-LPC": "clrlcgsbdii.in2p3.fr",
"IN2P3-LPSC": "lpsc-bdii.in2p3.fr",
"IN2P3-SUBATECH": "nanlcg01.in2p3.fr",
"INDIACMS-TIFR": "apel.indiacms.res.in",
"INFN-BARI": "gridba2.ba.infn.it",
"INFN-CATANIA": "alifarm10.ct.infn.it",
"INFN-CNAF-LHCB": "sg01-lhcb-t2.cr.cnaf.infn.it",
"INFN-FRASCATI": "atlasbdii.lnf.infn.it",
"INFN-LNL-2": "t2-sbdii.lnl.infn.it",
"INFN-MILANO-ATLASC": "t2-bdii.mi.infn.it",
"INFN-NAPOLI-ATLAS": "atlas-bdii.na.infn.it",
"INFN-PISA": "gridbdii0.pi.infn.it",
"INFN-ROMA1": "atlas-bdii.roma1.infn.it",
"INFN-ROMA1-CMS": "cmsrm-bdii.roma1.infn.it",
"INFN-T1" : "sg01-lcg.cr.cnaf.infn.it",
"INFN-TORINO": "t2-bdii-01.to.infn.it",
"ITEP": "creamce1.itep.ru",
"JINR-LCG2": "lcgsite.jinr.ru",
"Kharkov-KIPT-LCG2": "cms-eth0-1.kipt.kharkov.ua",
"KR-KISTI-GCRT-01": "sbdii-gcrt1.sdfarm.kr",
"KR-KISTI-GSDC-01" : "sbdii-gsdc1.sdfarm.kr",
"LCG_KNU": "cluster51.knu.ac.kr",
"LIP-Coimbra": "grid003.gridc.lip.pt",
"LIP-Lisbon": "site-bdii.lip.pt",
"LRZ-LMU": "lcg-lrz-ce0.grid.lrz.de",
"MPPMU": "grid-bdii.rzg.mpg.de",
"NCBJ-CIS": "bdii.cis.gov.pl",
"NCG-INGRID-PT": "sbdii01.ncg.ingrid.pt",
"NCP-LCG2": "pcncp26.ncp.edu.pk",
"NDGF-T1" : "bdii.ndgf.org",
"NIHAM": "alice003.nipne.ro",
"NIKHEF-ELPROD" : "siteinfo03.nikhef.nl",
"NO-NORGRID-T2": "bdii-no-t2.ndgf.org",
"pic" : "site-bdii.pic.es",
"praguelcg2": "sbdii1.farm.particle.cz",
"PSNC": "bdii.reef.man.poznan.pl",
"RAL-LCG2" : "site-bdii.gridpp.rl.ac.uk",
"RO-02-NIPNE": "baaf01.nipne.ro",
"RO-07-NIPNE": "tbit01.nipne.ro",
"RO-11-NIPNE": "lhcb-ce.nipne.ro",
"RO-13-ISS": "grid04.spacescience.ro",
"RO-14-ITIM": "ecream.itim-cj.ro",
"RO-16-UAIC": "ce-grid.grid.uaic.ro",
"RRC-KI": "gate.grid.kiae.ru",
"ru-Moscow-FIAN-LCG2": "ce1.grid.lebedev.ru",
"ru-Moscow-SINP-LCG2": "lcg02.sinp.msu.ru",
"ru-PNPI": "cluster.pnpi.nw.ru",
"RU-Protvino-IHEP": "bdii0002.m45.ihep.su",
"RU-SPbSU": "alice23.spbu.ru",
"Ru-Troitsk-INR-LCG2": "grinr09.inr.troitsk.ru",
"RWTH-Aachen": "grid-mon.physik.rwth-aachen.de",
"SAMPA": "sampabdii.if.usp.br",
"SARA-MATRIX": "sitebdii.grid.sara.nl",
"SE-SNIC-T2": "bdii-se-t2.ndgf.org",
"SFU-LCG2": "wormhole.westgrid.ca",
"SiGNET": "dodo.ijs.si",
"T2-TH-ALICE-NSTDA": "curium.lsr.nectec.or.th",
"T2_Estonia": "bdii.hep.kbfi.ee",
"Taiwan-LCG2" : "w-bdii.grid.sinica.edu.tw",
"TECHNION-HEP": "tech-bdii.hep.technion.ac.il",
"TOKYO-LCG2": "lcg-sitebdii01.icepp.jp",
"TR-03-METU": "cox01.grid.metu.edu.tr",
"TR-10-ULAKBIM": "kalkan1.ulakbim.gov.tr",
"TRIUMF-LCG2" : "site-bdii.triumf.ca",
"TW-FTT": "f-sbdii01.grid.sinica.edu.tw",
"UA-BITP": "ce.bitp.kiev.ua",
"UA-KNU": "gris.univ.kiev.ua",
"UAM-LCG2": "gridbdiisite.ft.uam.es",
"UB-LCG2": "hep-bdii.ecm.ub.es",
"UKI-LT2-Brunel": "dc2-grid-69.brunel.ac.uk",
"UKI-LT2-IC-HEP": "bdii.grid.hep.ph.ic.ac.uk",
"UKI-LT2-QMUL": "bdii01.htc.esc.qmul",
"UKI-LT2-RHUL": "sbdii2.ppgrid1.rhul.ac.uk",
"UKI-LT2-UCL-HEP": "lcg-bdii01.hep.ucl.ac.uk",
"UKI-NORTHGRID-LANCS-HEP": "fal-pygrid-14.lancs.ac.uk",
"UKI-NORTHGRID-LIV-HEP": "hepgrid4.ph.liv.ac.uk",
"UKI-NORTHGRID-MAN-HEP": "vm4.tier2.hep.manchester.ac.uk",
"UKI-NORTHGRID-SHEF-HEP": "lcg.shef.ac.uk",
"UKI-SCOTGRID-DURHAM": "site-bdii.dur.scotgrid.ac.uk",
"UKI-SCOTGRID-ECDF": "info2.glite.ecdf.ed.ac.uk",
"UKI-SCOTGRID-GLASGOW": "svr030.gla.scotgrid.ac.uk",
"UKI-SOUTHGRID-BHAM-HEP": "epgr09.ph.bham.ac.uk",
"UKI-SOUTHGRID-BRIS-HEP": "lcgbdii.phy.bris.ac.uk",
"UKI-SOUTHGRID-CAM-HEP": "vserv08.hep.phy.cam.ac.uk",
"UKI-SOUTHGRID-OX-HEP": "t2bdii05.physics.ox.ac.uk",
"UKI-SOUTHGRID-RALPP": "heplnv140.pp.rl.ac.uk",
"UKI-SOUTHGRID-SUSX": "grid-bdii.hpc.susx.ac.uk",
"UNIANDES": "piaroa.uniandes.edu.co",
"UNIBE-LHEP": "dpm.lhep.unibe.ch",
"UNI-FREIBURG": "bdii.bfg.uni-freiburg.de",
"USC-LCG2": "bdii.inv.usc.es",
"WEIZMANN-LCG2": "wipp-bdii.weizmann.ac.il",
"wuppertalprod": "grid-bdii.physik.uni-wuppertal.de"
}

lhcb_site_bdiis = {
"ARAGRID-CIENCIAS": "sbdiic-iber.bifi.unizar.es",
"AUVEGRID": "obssbdii.univ-bpclermont.fr",
"BG01-IPP": "sbdii.ipp.acad.bg",
"BIFI": "sbdii-egi.bifi.unizar.es",
"BMEGrid": "mon.hpc.iit.bme.hu",
"CBFP": "site-bdii.cat.cbpf.br",
"CERN-PROD" : "prod-bdii.cern.ch",
"CSCS-LCG2": "sbdii02.lcg.cscs.ch",
"CYFRONET-LCG2": "sbdii.grid.cyf-kr.edu.pl",
"DESY-HH": "grid-giis1.desy.de",
"EFDA-JET": "grid005.jet.efda.org",
"FZK-LCG2" : "giis-fzk.gridka.de",
"GR-04-FORTH-ICS": "grid001.ics.forth.gr",
"GRIF": "grid14.lal.in2p3.fr",
"GRISU-UNINA": "grisusitebdii.scope.unina.it",
"CY-01-KIMON": "sbdii.grid.ucy.ac.cy",
"ICM": "apel.grid.icm.edu.pl",
"IFJ-PAN-BG": "fwe02.ifj.edu.pl",
"IL-TAU-HEP": "tau-bdii.hep.tau.ac.il",
"IN2P3-CC": "cclcgip03.in2p3.fr",
"IN2P3-CC-T2": "cclcgip05.in2p3.fr",
"IN2P3-CPPM": "marbdii.in2p3.fr",
"IN2P3-LAPP": "lapp-site01.in2p3.fr",
"IN2P3-LPC": "clrlcgsbdii.in2p3.fr",
"INFN-BOLOGNA-T3": "sgbo-t3.cr.cnaf.infn.it",
"INFN-CATANIA": "alifarm10.ct.infn.it",
"INFN-CNAF-LHCB": "sg01-lhcb-t2.cr.cnaf.infn.it",
"INFN-FERRARA": "gridsite.fe.infn.it",
"INFN-FRASCATI": "atlasbdii.lnf.infn.it",
"INFN-LNL-2": "t2-sbdii.lnl.infn.it",
"INFN-MILANO-ATLASC": "t2-bdii.mi.infn.it",
"INFN-NAPOLI-ATLAS": "atlas-bdii.na.infn.it",
"INFN-PADOVA": "prod-bdii-02.pd.infn.it",
"INFN-PISA": "gridbdii0.pi.infn.it",
"INFN-ROMA2": "gridvm02.roma2.infn.it",
"INFN-T1" : "sg01-lcg.cr.cnaf.infn.it",
"INFN-TORINO": "t2-bdii-01.to.infn.it",
"INFN-TRIESTE": "gridbdii.ts.infn.it",
"ITEP": "creamce1.itep.ru",
"ITWM": "fornax-bdii.itwm.fhg.de",
"JINR-LCG2": "lcgsite.jinr.ru",
"NCBJ-CIS": "bdii.cis.gov.pl",
"NIKHEF-ELPROD" : "siteinfo03.nikhef.nl",
"PSNC": "bdii.reef.man.poznan.pl",
"RAL-LCG2" : "site-bdii.gridpp.rl.ac.uk",
"RO-07-NIPNE": "tbit01.nipne.ro",
"RO-11-NIPNE": "lhcb-ce.nipne.ro",
"RO-15-NIPNE": "tblb01.nipne.ro",
"RRC-KI": "gate.grid.kiae.ru",
"RRC-KI-T1": "taxer.t1.grid.kiae.ru",
"RU-Protvino-IHEP": "bdii0002.m45.ihep.su",
"RU-SPbSU": "alice23.spbu.ru",
"RUG-CIT": "columba.grid.rug.nl",
"Ru-Troitsk-INR-LCG2": "grinr09.inr.troitsk.ru",
"SARA-MATRIX": "sitebdii.grid.sara.nl",
"SNS-PISA": "bdii.sns.it",
"TECHNION-HEP": "tech-bdii.hep.technion.ac.il",
"UB-LCG2": "hep-bdii.ecm.ub.es",
"UKI-LT2-Brunel": "dc2-grid-69.brunel.ac.uk",
"UKI-LT2-IC-HEP": "bdii.grid.hep.ph.ic.ac.uk",
"UKI-LT2-QMUL": "bdii01.htc.esc.qmul",
"UKI-LT2-RHUL": "sbdii2.ppgrid1.rhul.ac.uk",
"UKI-NORTHGRID-LANCS-HEP": "fal-pygrid-14.lancs.ac.uk",
"UKI-NORTHGRID-LIV-HEP": "hepgrid4.ph.liv.ac.uk",
"UKI-NORTHGRID-MAN-HEP": "vm4.tier2.hep.manchester.ac.uk",
"UKI-NORTHGRID-SHEF-HEP": "lcg.shef.ac.uk",
"UKI-SCOTGRID-DURHAM": "site-bdii.dur.scotgrid.ac.uk",
"UKI-SCOTGRID-ECDF": "info2.glite.ecdf.ed.ac.uk",
"UKI-SCOTGRID-GLASGOW": "svr030.gla.scotgrid.ac.uk",
"UKI-SOUTHGRID-BHAM-HEP": "epgr09.ph.bham.ac.uk",
"UKI-SOUTHGRID-BRIS-HEP": "lcgbdii.phy.bris.ac.uk",
"UKI-SOUTHGRID-CAM-HEP": "vserv08.hep.phy.cam.ac.uk",
"UKI-SOUTHGRID-OX-HEP": "t2bdii05.physics.ox.ac.uk",
"UKI-SOUTHGRID-RALPP": "heplnv140.pp.rl.ac.uk",
"UNI-DORTMUND": "udo-bdii01.grid.tu-dortmund.de",
"UNINA-EGEE": "sitebdii.scope.unina.it",
"USC-LCG2": "bdii.inv.usc.es",
"WCSS64": "tatooine.wcss.pl",
"WEIZMANN-LCG2": "wipp-bdii.weizmann.ac.il",
"pic": "site-bdii.pic.es",
"ru-Moscow-SINP-LCG2": "lcg02.sinp.msu.ru",
"ru-PNPI": "cluster.pnpi.nw.ru"
}

lhcb_names_dict = {
"ARAGRID-CIENCIAS": "LCG.ARAGRID-CIENCIAS.es",
"AUVEGRID": "LCG.AUVER.fr",
"BG01-IPP": "LCG.IPP.bg",
"BIFI": "LCG.BIFI.es",
"BMEGrid": "LCG.BMEGrid.hu",
"CBFP": "LCG.CBPF.br",
"CERN-PROD" : "LCG.CERN.ch",
"CSCS-LCG2": "LCG.CSCS.ch",
"CY-01-KIMON": "LCG.KIMON.cy",
"CYFRONET-LCG2": "LCG.Krakow.pl",
"DESY-HH": "LCG.DESY.de",
"EFDA-JET": "LCG.EFDA.uk",
"FZK-LCG2" : "LCG.GRIDKA.de",
"GR-04-FORTH-ICS": "LCG.GR-04.gr",
"GRIF": "LCG.LAL.fr",
"GRISU-UNINA": "LCG.GRISU-UNINA.it",
"ICM": "LCG.ICM.pl",
"IFJ-PAN-BG": "LCG.IFJ-PAN.pl",
"IL-TAU-HEP": "LCG.TAU.il",
"IN2P3-CC": "LCG.IN2P3.fr",
"IN2P3-CC-T2": "LCG.IN2P3-T2.fr",
"IN2P3-CPPM": "LCG.CPPM.fr",
"IN2P3-LAPP": "LCG.LAPP.fr",
"IN2P3-LPC": "LCG.LPC.fr",
"INFN-BOLOGNA-T3": "LCG.Bologna.it",
"INFN-CATANIA": "LCG.Catania.it",
"INFN-CNAF-LHCB": "LCG.CNAF-T2.it",
"INFN-FERRARA": "LCG.Ferrara.it",
"INFN-FRASCATI": "LCG.Frascati.it",
"INFN-LNL-2": "LCG.Legnaro.it",
"INFN-MILANO-ATLASC": "LCG.MILANO-ATLASC.it",
"INFN-NAPOLI-ATLAS": "LCG.NAPOLI-ATLAS.it",
"INFN-PADOVA": "LCG.Padova.it",
"INFN-PISA": "LCG.Pisa.it",
"INFN-ROMA2": "LCG.Roma.it",
"INFN-T1" : "LCG.CNAF.it",
"INFN-TORINO": "LCG.Torino.it",
"INFN-TRIESTE": "LCG.Trieste.it",
"ITEP": "LCG.ITEP.ru",
"ITWM": "LCG.ITWM.de",
"JINR-LCG2": "LCG.JINR.ru",
"NCBJ-CIS": "LCG.NCBJ.pl",
"NIKHEF-ELPROD" : "LCG.NIKHEF.nl",
"PSNC": "LCG.PSNC.pl",
"RAL-LCG2" : "LCG.RAL.uk",
"RO-07-NIPNE": "LCG.NIPNE-07.ro",
"RO-11-NIPNE": "LCG.NIPNE-11.ro",
"RO-15-NIPNE": "LCG.NIPNE-15.ro",
"RRC-KI": "LCG.KIAE.ru",
"RRC-KI-T1": "LCG.RRCKI.ru",
"RU-Protvino-IHEP": "LCG.IHEP.su",
"RU-SPbSU": "LCG.SPBU.ru",
"RUG-CIT": "LCG.RUG.nl",
"Ru-Troitsk-INR-LCG2": "LCG.INR.ru",
"SARA-MATRIX": "LCG.SARA.nl",
"SNS-PISA": "LCG.SNS-PISA.it",
"TECHNION-HEP": "LCG.Haifa.il",
"UB-LCG2": "LCG.Barcelona.es",
"UKI-LT2-Brunel": "LCG.UKI-LT2-Brunel.uk",
"UKI-LT2-IC-HEP": "LCG.UKI-LT2-IC-HEP.uk",
"UKI-LT2-QMUL": "LCG.UKI-LT2-QMUL.uk",
"UKI-LT2-RHUL": "LCG.UKI-LT2-RHUL.uk",
"UKI-NORTHGRID-LANCS-HEP": "LCG.Lancashire.uk",
"UKI-NORTHGRID-LIV-HEP": "LCG.Liverpool.uk",
"UKI-NORTHGRID-MAN-HEP": "LCG.Manchester.uk",
"UKI-NORTHGRID-SHEF-HEP": "LCG.Sheffield.uk",
"UKI-SCOTGRID-DURHAM": "LCG.Durham.uk",
"UKI-SCOTGRID-ECDF": "LCG.ECDF.uk",
"UKI-SCOTGRID-GLASGOW": "LCG.Glasgow.uk",
"UKI-SOUTHGRID-BHAM-HEP": "LCG.BHAM-HEP.uk",
"UKI-SOUTHGRID-BRIS-HEP": "LCG.Bristol.uk",
"UKI-SOUTHGRID-CAM-HEP": "LCG.Cambridge.uk",
"UKI-SOUTHGRID-OX-HEP": "LCG.Oxford.uk",
"UKI-SOUTHGRID-RALPP": "LCG.RAL-HEP.uk",
"UNI-DORTMUND": "LCG.Dortmund.de",
"UNINA-EGEE": "LCG.UNINA.it",
"USC-LCG2": "LCG.USC.es",
"WCSS64": "LCG.WCSS.pl",
"WEIZMANN-LCG2": "LCG.WEIZMANN.il",
"pic": "LCG.PIC.es",
"ru-Moscow-SINP-LCG2": "LCG.SINP.ru",
"ru-PNPI": "LCG.PNPI.ru"
}
