#
# List of site bdiis used by the dashboard scripts
#
# Note: List of GOCDB sites updated from GOCDB on 10.03.2014
#       List of WLCG sites updated from REBUS on 05.12.2013
#       List of LHCb sites updated from DIRAC on 06.12.2013
#       List of CMS sites updated from siteDB on 14.02.2014 
#
###############################################################

gocdb_bdiis = {
"AEGIS01-IPB-SCL" : "cream.ipb.ac.rs:2170",
"AEGIS02-RCUB" : "grid01.rcub.bg.ac.rs:2170",
"AEGIS03-ELEF-LEDA" : "grid01.elfak.ni.ac.rs:2170",
"AEGIS04-KG" : "cluster1.csk.kg.ac.rs:2170",
"AEGIS05-ETFBG" : "grid-ce.etf.bg.ac.rs:2170",
"AEGIS07-IPB-ATLAS" : "ce-atlas.ipb.ac.rs:2170",
"AEGIS09-FTN-KM" : "cream.ftn.pr.ac.rs:2170",
"AEGIS10-VINCA-CMS" : "ce-cms.vinca.rs:2170",
"AEGIS11-MISANU" : "cream.mi.sanu.ac.rs:2170",
"AGH-ICSR" : "xxxx.icsr.agh.edu.pl:2170",
"AL-01-FIT" : "ce.fit.upt.al:2170",
"alberta-lcg2" : "lcgce01.cpp.ualberta.ca:2170",
"AM-02-SEUA" : "bdii.seua-cluster.grid.am:2170",
"AM-03-YSU" : "bdii.ysu-cluster.grid.am:2170",
"AM-04-YERPHI" : "bdii.yerphi-cluster.grid.am:2170",
"AM-05-YSU" : "bdii.ysu-cluster2.grid.am:2170",
"AMD64.PSNC.PL" : "fangorn.man.poznan.pl:2170",
"ARAGRID-CIENCIAS" : "sbdiic-iber.bifi.unizar.es:2170",
"ARAGRID-HUESCA" : "sbdiih-iber.bifi.unizar.es:2170",
"ARAGRID-TERUEL" : "sbdiic-iber.bifi.unizar.es:2170",
"AREA-BO" : "grid1.ira.inaf.it:2170",
"ARNES" : "kser.arnes.si:2170",
"ATLAND" : "atlandsitebdii.fis.puc.cl:2170",
"AUVERGRID" : "obssbdii.univ-bpclermont.fr:2170",
"atos" : "bender.ijs.si:2170",
"Australia-ATLAS" : "agsite.atlas.unimelb.edu.au:2170",
"Australia-T2" : "t2site.mel.coepp.org.au:2170",
"BA-01-ETFBL" : "c01.grid.etfbl.net:2170",
"BCBR" : "bdii1-enmr.science.uu.nl:2170",
"BEIJING-CNIC-LCG2-IA64" : "ce-lcg.sdg.ac.cn:2170",
"BEIJING-LCG2" : "lcg002.ihep.ac.cn:2170",
"BEgrid-BELNET" : "sitebdii.begrid.be:2170",
"BEgrid-KULeuven" : "kg-ce01.cc.kuleuven.be:2170",
"BEgrid-UGent" : "gridsbdii.atlantis.ugent.be:2170",
"BEgrid-ULB-VUB" : "sitebdii.iihe.ac.be:2170",
"BEgrid-UniversiteitAntwerpen" : "ce01.cmi.ua.ac.be:2170",
"BG-INRNE" : "ds2.inrne.bas.bg:2170",
"BG01-IPP" : "sbdii.ipp.acad.bg:2170",
"BG02-IM" : "sbdii.imbm.bas.bg:2170",
"BG03-NGCC" : "sbdii.ngcc.acad.bg:2170",
"BG04-ACAD" : "ce02.grid.acad.bg:2170",
"BG05-SUGrid" : "sbdii.grid.uni-sofia.bg:2170",
"BG06-GPHI" : "sbdii.geophys.bas.bg:2170",
"BG07-EDU" : "ce-edu.grid.acad.bg:2170",
"BG08-MADARA" : "sbdii.grid.orgchm.bas.bg:2170",
"BIFI" : "sbdii-egi.bifi.unizar.es:2170",
"BIFI-IBERGRID" : "sbdii-iber.bifi.unizar.es:2170",
"BIOCOMP" : "duck-02.biocomp.unibo.it:2170",
"BMEGrid" : "mon.hpc.iit.bme.hu:2170",
"BMRZ-FRANKFURT" : "ce-enmr.chemie.uni-frankfurt.de:2170",
"BRGM-ORLEANS" : "egi-bdii.brgm.fr:2170",
"BUDAPEST" : "grid147.kfki.hu:2170",
"BY-BNTU" : "bdii.grid.bntu.by:2170",
"BY-JIPNR-SOSNY" : "npg4.basnet.by:2170",
"BY-NCPHEP" : "mirror.hep.by:2170",
"BY-UIIP" : "is.basnet.by:2170",
"BelGrid-UCL" : "ingrid.cism.ucl.ac.be:2170",
"CA-ALBERTA-WESTGRID-T2" : "cream01.atlas.ualberta.ca:2170",
"CA-MCGILL-CLUMEQ-PPS" : "ce01.clumeq.mcgill.ca:2170",
"CA-MCGILL-CLUMEQ-T2" : "site-bdii.clumeq.mcgill.ca:2170",
"CA-SCINET-T2" : "lcg-se3.scinet.utoronto.ca:2170",
"CA-TRIUMF-T2K" : "repo.nd280.org:2170",
"CA-VICTORIA-WESTGRID-T2" : "charon02.westgrid.ca:2170",
"CAFPE-GRANADA" : "cream-cafpegrid.ugr.es:2170",
"CAMK" : "bdii.cta.camk.edu.pl:2170",
"carletonlcg02" : "lcg02.physics.carleton.ca:2135",
"CBPF" : "site-bdii.cat.cbpf.br:2170",
"CERN-PROD" : "prod-bdii.cern.ch:2170",
"CERN_PPS" : "lxbra2503.cern.ch:2170",
"CESGA" : "sitebdii.egi.cesga.es:2170",
"cesga-pps" : "pps-ce.egee.cesga.es:2170",
"cesic-unical" : "bdii.cesic.unical.it:2170",
"CESNET-MetaCloud": "carach5.ics.muni.cz:2170",
"CETA-GRID" : "bdii-rc.ceta-ciemat.es:2170",
"CFP-IST" : "golp-bdii.ist.utl.pt:2170",
"CGG-LCG2" : "ce2.egeode.org:2170",
"CICESE" : "gisela-bdii.cicese.mx:2170",
"CIEMAT-LCG2" : "lcg03.ciemat.es:2170",
"CIEMAT-TIC" : "bdii-tic.ciemat.es:2170",
"CIPKeBiP" : "gender.ijs.si:2170",
"CIRMMP" : "ce-enmr.cerm.unifi.it:2170",
"CMS-BURT-ITB" : "is-itb.grid.iu.edu:2180",
"CN-BEIJING-PKU" : "grid04.phy.pku.edu.cn:2170",
"CNB-LCG2" : "mallarme.cnb.csic.es:2170",
"CNR-ILC-PISA" : "gridbdii.ilc.cnr.it:2170",
"CNR-PROD-PISA" : "lcg-ce.research-infrastructures.eu:2170",
"CREATIS-INSA-LYON" : "linux1.grid.creatis.insa-lyon.fr:2170",
"CRS4" : "egridglitece.crs4.it:2170",
"CSC" : "site-bdii.fgi.csc.fi:2170",
"CSCS-LCG2" : "bdii.lcg.cscs.ch:2170",
"CSIC-BELLATERRA" : "bdii.grid-bellaterra.csic.es:2170",
"CY-01-KIMON" : "sbdii.grid.ucy.ac.cy:2170",
"CY-02-CYGRID-CERT" : "ce201.grid.ucy.ac.cy:2170",
"CYF-CERTIF-TB" : "pl-ce.grid.cyf-kr.edu.pl:2170",
"CYFRONET-IA64" : "ares02.cyf-kr.edu.pl:2170",
"CYFRONET-LCG2" : "sbdii.grid.cyf-kr.edu.pl:2170",
"ClusterUL" : "ce01.fam.ulusiada.pt:2170",
"DESY-HH" : "grid-giis.desy.de:2170",
"DESY-ZN" : "lcg-giis.ifh.de:2170",
"DI-UMinho" : "ce.egee.di.uminho.pt:2170",
"EELA-UNLP" : "ce01.unlp.edu.ar:2170",
"EELA-UTFSM" : "site.hpc.utfsm.cl:2170",
"EENet" : "bdii.grid.eenet.ee:2170",
"EFDA-JET" : "grid005.jet.efda.org:2170",
"ESA-ESAC" : "glite-site-bdii.esac.esa.int:2170",
"ESA-ESRIN" : "grid-eo-engine04.esrin.esa.int:2170",
"ESRF" : "grid-sbdii.esrf.eu:2170",
"FBF-Brescia-IT" : "srv6.fatebenefratelli.it:2170",
"FENIX" : "bdii.fcfm.buap.mx:2170",
"FI-LCG2" : "grid.fi.lt:2170",
"urn:ad:FI_AA" : "asterope-grid.abo.fi:2135",
"urn:ad:FI_Aalto" : "grid.triton.aalto.fi:2135",
"FI_HIP_T2" : "bdii.hip.fi:2170",
"urn:ad:FI_Helsinki" : "alcyone-grid.grid.helsinki.fi:2135",
"urn:ad:FI_JYU" : "electra-grid.jyu.fi:2135",
"urn:ad:FI_LUT" : "celaeno-grid.lut.fi:2135",
"urn:ad:FI_Oulu" : "taygeta-grid.oulu.fi:2135",
"urn:ad:FI_TUT" : "merope-grid.cc.tut.fi:2135",
"urn:ad:FI_UEF" : "maia-grid.uef.fi:2135",
"urn:ad:FI_UTU" : "pleione-grid.utu.fi:2135",
"FMPhI-UNIBA" : "lcgmonitor.dnp.fmph.uniba.sk:2170",
"FRANCE-GRILLES-TESTBED" : "cctbsitebdii01.in2p3.fr:2170",
"FZJ" : "site-bdii.fz-juelich.de:2170",
"FZK-LCG2" : "giis-fzk.gridka.de:2170",
"FZU-IPV6" : "cream.ipv6.farm.particle.cz:2170",
"GARR-01-DIR" : "gridsrv4-4.dir.garr.it:2170",
"GE-01-GRENA" : "cream.sg.grena.ge:2170",
"GILDA-INFN-CATANIA" : "gildact-sb.ct.infn.it:2170",
"GILDA-NeSC" : "dc01.nesc.ed.ac.uk:2170",
"GILDA-PADOVA" : "gilda-01.pd.infn.it:2170",
"GILDA-SIRIUS" : "sirius-sb.ct.infn.it:2170",
"GILDA-VEGA" : "vega-ce.ct.infn.it:2170",
"GR-01-AUTH" : "sbdii.grid.auth.gr:2170",
"GR-02-UoM" : "alexander.it.uom.gr:2170",
"GR-03-HEPNTUA" : "ce.hep.ntua.gr:2170",
"GR-04-FORTH-ICS" : "grid001.ics.forth.gr:2170",
"GR-05-DEMOKRITOS" : "arxiloxos1.inp.demokritos.gr:2170",
"GR-06-IASA" : "site-bdii02.marie.hellasgrid.gr:2170",
"GR-07-UOI-HEPLAB" : "grid03.physics.uoi.gr:2170",
"GR-08-CEID" : "ce01.grid.ceid.upatras.gr:2170",
"GR-09-UoA" : "dl01.di.uoa.gr:2170",
"GR-10-UOI" : "cream01.grid.uoi.gr:2170",
"GR-11-UPATRAS" : "bdii.csl.ee.upatras.gr:2170",
"GRID-UNISON" : "bdii.grid.uson.mx:2170",
"GRIF" : "bdii.grif.fr:2170",
"GRISU-COMETA-INAF-CT" : "inaf-ce-01.ct.pi2s2.it:2170",
"GRISU-COMETA-INFN-CT" : "infn-ce-02.ct.pi2s2.it:2170",
"grisu-cometa-ing-messina" : "unime-ce-01.me.pi2s2.it:2170",
"grisu-cometa-unict-diit" : "unict-diit-ce-01.ct.pi2s2.it:2170",
"grisu-cometa-unict-dmi" : "unict-dmi-ce-01.ct.pi2s2.it:2170",
"grisu-cometa-unipa" : "unipa-ce-01.pa.pi2s2.it:2170",
"grisu-cybersar-cagliari" : "bdii-site-cyb.ca.infn.it:2170",
"GRISU-ENEA-GRID" : "bdii-site.frascati.enea.it:2170",
"grisu-spaci-lecce" : "ce2.egee.unisalento.it:2170",
"GRISU-SPACI-NAPOLI" : "spacina-sitebdii.scope.unina.it:2170",
"GRISU-UNINA" : "grisusitebdii.scope.unina.it:2170",
"GSI-LCG2" : "lcg-bdii.gsi.de:2170",
"GoeGrid" : "bdii.goegrid.gwdg.de:2170",
"HEPHY-UIBK" : "test-ui.uibk.ac.at:2170",
"HG-01-GRNET" : "mon.isabella.grnet.gr:2170",
"HG-02-IASA" : "site-bdii01.marie.hellasgrid.gr:2170",
"HG-03-AUTH" : "sbdii.afroditi.hellasgrid.gr:2170",
"HG-04-CTI-CEID" : "mon.kallisto.hellasgrid.gr:2170",
"HG-05-FORTH" : "cream-ce01.ariagni.hellasgrid.gr:2170",
"HG-06-EKT" : "mon.athena.hellasgrid.gr:2170",
"HG-08-Okeanos" : "snf-189279.vm.okeanos.grnet.gr:2170",
"HG-09-Okeanos-Cloud" : "okeanos-is.hellasgrid.gr:2170",
"HK-HKU-CC-01" : "glite05.grid.hku.hk:2170",
"HPTC-LCG2" : "ce.prd.hp.com:2170",
"HPTC-LCG2ia64" : "ice.prd.hp.com:2170",
"HR-01-RBI" : "grid1.irb.hr:2170",
"HRL_KZ" : "bdii-site.haifa.il.ibm.com:2170",
"HTC-BIGGRID" : "phoebe.htc.biggrid.nl:2170",
"Hephy-Vienna" : "bdii.oeaw.ac.at:2170",
"IAA-CSIC" : "bdii.iaa.csic.es:2170",
"IBCP-GBIO" : "grive14.ibcp.fr:2170",
"ICEAGE-CATANIA" : "iceage-sb-01.ct.infn.it:2170",
"ICM" : "apel.grid.icm.edu.pl:2170",
"ICM-PLGRID" : "plgrid-123.icm.edu.pl:2170",
"ICN-UNAM" : "tochtli.nucleares.unam.mx:2170",
"IEETA" : "axon-g02.ieeta.pt:2170",
"IEPSAS-Kosice" : "glmon-iep-grid.saske.sk:2170",
"IFCA-LCG2" : "gridiis01.ifca.es:2170",
"IFIC-LCG2" : "sbdii.ific.uv.es:2170",
"IFISC-GRID" : "nureddunasb.uib-csic.es:2170",
"IFJ-PAN-BG" : "fwe02.ifj.edu.pl:2170",
"IGI-BOLOGNA" : "bdii.italiangrid.it:2170",
"IISAS-Bratislava" : "sbdii.ui.savba.sk:2170",
"IISAS-FedCloud" : "nova.ui.savba.sk:2170",
"IISAS-GILDA" : "dgt01.ui.savba.sk:2170",
"IL-BGU" : "cs-grid1.bgu.ac.il:2170",
"IL-BGU-PPS" : "ce02-pps.bgu.ac.il:2170",
"IL-IUCC" : "grim-ce.iucc.ac.il:2170",
"IL-TAU-CS" : "ce-01.cs.tau.ac.il:2170",
"IL-TAU-HEP" : "tau-bdii.hep.tau.ac.il:2170",
"IL_COMP" : "ngi-il-bdii13.isragrid.org.il:2170",
"IL_IUCC_IG" : "ngi-il-bdii11.isragrid.org.il:2170",
"IMCSUL" : "bdii-imcsul.ndgf.org:2170",
"IMCSUL-INF" : "sbdii02.grid.lumii.lv:2170",
"IN-DAE-VECC-01" : "gridce01.tier2-kol.res.in:2170",
"IN-DAE-VECC-02" : "dcache-server.tier2-kol.res.in:2170",
"IN2P3-CC" : "cclcgip01.in2p3.fr:2170",
"IN2P3-CC-T2" : "cclcgip03.in2p3.fr:2170",
"IN2P3-CPPM" : "marbdii.in2p3.fr:2170",
"IN2P3-IPNL" : "lyobdii.in2p3.fr:2170",
"IN2P3-IRES" : "sbgbdii1.in2p3.fr:2170",
"IN2P3-LAPP" : "lapp-site01.in2p3.fr:2170",
"IN2P3-LPC" : "clrlcgsbdii.in2p3.fr:2170",
"IN2P3-LPSC" : "lpsc-bdii.in2p3.fr:2170",
"IN2P3-SUBATECH" : "nansbdii.in2p3.fr:2170",
"inaf-trieste" : "grid001.oat.ts.astro.it:2170",
"INAF-TS" : "ce01.oats.inaf.it:2170",
"INDIACMS-TIFR" : "apel.indiacms.res.in:2170",
"INFN-BARI" : "gridba2.ba.infn.it:2170",
"INFN-BOLOGNA" : "bobdii.bo.infn.it:2170",
"INFN-BOLOGNA-CMS" : "cmsboce.bo.infn.it:2170",
"INFN-BOLOGNA-T3" : "sgbo-t3.cr.cnaf.infn.it:2170",
"INFN-CAGLIARI" : "bdii-site.ca.infn.it:2170",
"INFN-CASCINA" : "grid-ce.virgo.infn.it:2170",
"INFN-CATANIA" : "alifarm10.ct.infn.it:2170",
"INFN-CATANIA-NEBULA" : "nebula-server-01.ct.infn.it:2170",
"INFN-CATANIA-STACK" : "stack-server-01.ct.infn.it:2170",
"INFN-CNAF-LHCB" : "sg01-lhcb-t2.cr.cnaf.infn.it:2170",
"INFN-COSENZA" : "linucs-bdii.cs.infn.it:2170",
"INFN-FERRARA" : "gridsite.fe.infn.it:2170",
"INFN-FIRENZE" : "grid001.fi.infn.it:2170",
"INFN-FRASCATI" : "atlasbdii.lnf.infn.it:2170",
"INFN-GENOVA" : "bdii02.ge.infn.it:2170",
"INFN-LECCE" : "bdii-1.le.infn.it:2170",
"INFN-LNL-2" : "t2-sbdii.lnl.infn.it:2170",
"INFN-LNS" : "grid-ce.lns.infn.it:2170",
"INFN-MIB" : "bdii.mib.infn.it:2170",
"INFN-MILANO" : "t2-ce-01.mi.infn.it:2170",
"INFN-MILANO-ATLASC" : "t2-bdii.mi.infn.it:2170",
"infn-napoli" : "griditce01.na.infn.it:2170",
"INFN-NAPOLI-ARGO" : "argoce01.na.infn.it:2170",
"INFN-NAPOLI-ATLAS" : "atlas-bdii.na.infn.it:2170",
"INFN-NAPOLI-CMS" : "cmsce01.na.infn.it:2170",
"INFN-NAPOLI-PAMELA" : "pamelace01.na.infn.it:2170",
"INFN-PADOVA" : "prod-bdii-02.pd.infn.it:2170",
"INFN-PADOVA-CMS" : "t3-ce-01.pd.infn.it:2170",
"INFN-PADOVA-CREAMTEST" : "cream-27.pd.infn.it:2170",
"INFN-PARMA" : "grid-bdii.pr.infn.it:2170",
"INFN-PAVIA" : "grid-bdii.pv.infn.it:2170",
"INFN-PERUGIA" : "cream-bdii.pg.infn.it:2170",
"INFN-PISA" : "gridbdii0.pi.infn.it:2170",
"INFN-ROMA1" : "atlas-bdii.roma1.infn.it:2170",
"INFN-ROMA1-CMS" : "cmsrm-bdii.roma1.infn.it:2170",
"INFN-ROMA1-TEO" : "teo-se-01.roma1.infn.it:2170",
"INFN-ROMA1-VIRGO" : "virgo-ce.roma1.infn.it:2170",
"INFN-ROMA2" : "gridvm02.roma2.infn.it:2170",
"INFN-ROMA3" : "gridsrv-02.roma3.infn.it:2170",
"INFN-T1" : "sg01-lcg.cr.cnaf.infn.it:2170",
"INFN-TORINO" : "t2-bdii-01.to.infn.it:2170",
"INFN-TRIESTE" : "gridbdii.ts.infn.it:2170",
"INSU01-PARIS" : "sitebdii.ipgp.fr:2170",
"IPSL-IPGP-LCG2" : "egee-ce.datagrid.jussieu.fr:2170",
"IR-IPM-HEP" : "bdii.particles.ipm.ac.ir:2170",
"ISIS-UNIANDES" : "sisbdii.uniandes.edu.co:2170",
"ITB-BARI" : "beagle14.ba.itb.cnr.it:2170",
"ITEP" : "creamce1.itep.ru:2170",
"ITWM" : "fornax-bdii.itwm.fhg.de:2170",
"JINR-LCG2" : "lcgsite.jinr.ru:2170",
"JINR-T1" : "site.jinr-t1.ru:2170",
"JP-HIROSHIMA-WLCG" : "grid02.hepl.hiroshima-u.ac.jp:2170",
"JP-KEK-CRC-02" : "kek2-sbdii.cc.kek.jp:2170",
"KEELE-NGS" : "sitebdii.ngs.rl.ac.uk:2170",
"KMU-PRI-LCG2" : "grid.pri.kmu.lt:2170",
"KR-KISTI-GCRT-01" : "sbdii-gcrt1.sdfarm.kr:2170",
"KR-KISTI-GSDC-01" : "sbdii-gsdc1.sdfarm.kr:2170",
"KR-KISTI-HEP" : "hep001.kisti.re.kr:2170",
"KR-KNU-T3" : "cluster117.knu.ac.kr:2170",
"KR-UOS-SSCC" : "uosaf0006.sscc.uos.ac.kr:2170",
"KTH-CLOUD" : "bdii.cloud.pdc.kth.se:2170",
"KTU-BG-GLITE" : "ce.bg.ktu.lt:2170",
"KTU-ELEN-LCG2" : "pupa.elen.ktu.lt:2170",
"Kharkov-KIPT-LCG2" : "cms-eth0-1.kipt.kharkov.ua:2170",
"LCG-IL-OU" : "sBDII.grid.openu.ac.il:2170",
"lcg-ustc" : "ce2.lcg.ustc.edu.cn:2170",
"LCG_KNU" : "cluster51.knu.ac.kr:2170",
"LIP-Coimbra" : "grid003.gridc.lip.pt:2170",
"LIP-Lisbon" : "site-bdii.lip.pt:2170",
"LNCC-COMCIDIS" : "cream-ce.lncc.br:2170",
"LRZ-LMU" : "lcg-lrz-bdii.grid.lrz.de:2170",
"LSG-AMC" : "gb-ce-amc.amc.nl:2170",
"LSG-AMS" : "gb-sitebdii-ams.els.sara.nl:2170",
"LSG-EMC" : "gb-ce-emc.erasmusmc.nl:2170",
"LSG-HTC" : "sitebdii.htc.els.sara.nl:2170",
"LSG-HUB" : "ce.lsg.hubrecht.eu:2170",
"LSG-KG" : "gb-ce-kg.keygene.com:2170",
"LSG-KUN" : "gb-ce-kun.els.sara.nl:2170",
"LSG-LUMC" : "gb-ce-lumc.lumc.nl:2170",
"LSG-NKI" : "gb-ce-nki.els.sara.nl:2170",
"LSG-RUG" : "gb-ce-rug.sara.usor.nl:2170",
"LSG-TUD" : "gb-ce-tud.ewi.tudelft.nl:2170",
"LSG-UU" : "gb-ce-uu.science.uu.nl:2170",
"LSG-VU" : "ce.lsg.psy.vu.nl:2170",
"LSG-WUR" : "gb-ce-wur.els.sara.nl:2170",
"M3PEC" : "sbdii.m3pec.u-bordeaux1.fr:2170",
"MD-01-TUM" : "ce01.grid.renam.md:2170",
"MD-02-IMI" : "node06-02.imi.renam.md:2170",
"MD-03-USM" : "node03-03.usm.renam.md:2170",
"MD-04-RENAM" : "node02-04.grid.renam.md:2170",
"MK-01-UKIM_II" : "grid-ce.ii.edu.mk:2170",
"MK-02-ETF" : "grid-ce.feit.ukim.edu.mk:2170",
"MK-03-FINKI" : "ce.hpgcc.finki.ukim.mk:2170",
"MPI-K" : "grid-bdii.mpi-hd.mpg.de:2170",
"MPPMU" : "grid-bdii.rzg.mpg.de:2170",
"MREN-01-CIS" : "ce.grid.ac.me:2170",
"MSFG-MULTI" : "bdii.msfg.fr:2170",
"MSFG-OPEN" : "lptabdii.msfg.fr:2170",
"MY-MIMOS-GC-01" : "grid02.knowledgegrid.net.my:2170",
"MY-NM-NEUTRON" : "iridium.nuclearmalaysia.gov.my:2170",
"MY-UM-CRYSTAL" : "usnea.geranium.um.edu.my:2170",
"MY-UPM-BIRUNI-01" : "is.biruni.upm.my:2170",
"MY-UPM-UGRID-01" : "ce001.ugrid.upm.edu.my:2170",
"MY-UTM-GRID" : "is.utmgrid.utm.my:2170",
"NACAD_UFRJ" : "site-bdii.nacad.ufrj.br:2170",
"NCBJ-CIS" : "bdii.cis.gov.pl:2170",
"NCG-INGRID-PT" : "sbdii01.ncg.ingrid.pt:2170",
"NCP-LCG2" : "pcncp26.ncp.edu.pk:2170",
"glue12" : "benedict.grid.aau.dk:2135",
"NDGF-T1" : "bdii.ndgf.org:2170",
"NGI_BY_SERVICES" : "grid-portal.basnet.by:2170",
"NGI_IL" : "ngi-il-bdii11.isragrid.org.il:2170",
"NGI_IL_MED1" : "ngi-il-bdii12.isragrid.org.il:2170",
"local" : "topbdii.bitp.kiev.ua:2170",
"NGS-Cardiff" : "aconngs01.condor.cf.ac.uk:2135",
"local" : "grid.ecdf.ed.ac.uk:2135",
"NGS-HUDDERSFIELD" : "qgg.hud.ac.uk:2135",
"local" : "grid.lancs.ac.uk:2135",
"NGS-LEEDS" : "ngs.arc1.leeds.ac.uk:2170",
"local" : "vigg1.reading.ac.uk:2135",
"UniversityOfSheffield" : "ngsinfo.grid-support.ac.uk:2135",
"local" : "ngs.wmin.ac.uk:2135",
"NIHAM" : "alice003.nipne.ro:2170",
"NIKHEF-ELPROD" : "siteinfo03.nikhef.nl:2170",
"NO-NORGRID-T2" : "bdii-no-t2.ndgf.org:2170",
"NZ-UOA" : "glite-bdii.ceres.auckland.ac.nz:2170",
"OBSPM" : "bdii-local-grid.obspm.fr:2170",
"IUPUI-ITB" : "feynman.uits.iupui.edu:2135",
"pakgrid-lcg2" : "ce.pakgrid.org.pk:2170",
"PAKGRID3-LCG2" : "CE.hmc-3.com.pk:2170",
"PARIS-UREC-IPV6" : "bdii-ipv6-testbed.paris.urec.cnrs.fr:2170",
"pdc" : "site-bdii.pdc.kth.se:2170",
"PEARL-AMU" : "pearl.amu.edu.pl:2170",
"PH-ASTI-BUHAWI" : "buhawi.pscigrid.gov.ph:2170",
"PH-ASTI-DALUBHASAAN" : "dalubhasaan.pscigrid.gov.ph:2170",
"PH-ASTI-LIKNAYAN" : "mon.pscigrid.gov.ph:2170",
"PH-ATENEO" : "medgrid2.ateneo.edu:2170",
"PIC-PPS" : "ppsbdiisite01.pic.es:2170",
"PK-CIIT" : "cern-56-24-243.comsats.edu.pk:2170",
"PPS-CYFRONET" : "zeus75.cyf-kr.edu.pl:2170",
"PPS-ENG" : "grids02.eng.it:2170",
"PPS-IFIC" : "cg05.ific.uv.es:2170",
"PPS-LIP" : "pps-sbdii.lip.pt:2170",
"PPS-RAL" : "pps-ce-277.gridpp.rl.ac.uk:2170",
"PPS-RO-01-UPB" : "gw01.egee.grid.pub.ro:2170",
"PPS-SNS" : "dlgce.sns.it:2170",
"PPS-SiGNET" : "glitece.ijs.si:2170",
"PRISMA-INFN-BARI" : "prisma-cloud.ba.infn.it:2170",
"PSK_KIELCE" : "ce.egee.tu.kielce.pl:2170",
"PSNC" : "bdii.reef.man.poznan.pl:2170",
"PSNC-GILDA" : "gildace.reef.man.poznan.pl:2170",
"RAL-LCG2" : "site-bdii.gridpp.rl.ac.uk:2170",
"RC-GISELA-CETA" : "bdii-rc-gisela.ceta-ciemat.es:2170",
"RECAS-BARI" : "recas-ce.ba.infn.it:2170",
"RECAS-NAPOLI" : "recasna-sitebdii.unina.it:2170",
"RO-01-ICI" : "sbdii.grid.ici.ro:2170",
"RO-02-NIPNE" : "tbat01.nipne.ro:2170",
"RO-07-NIPNE" : "tbit01.nipne.ro:2170",
"RO-09-UTCN" : "ce01.mosigrid.utcluj.ro:2170",
"RO-11-NIPNE" : "lhcb-ce.nipne.ro:2170",
"RO-12-ICI" : "se.rncgrid.ici.ro:2170",
"RO-13-ISS" : "grid04.spacescience.ro:2170",
"RO-14-ITIM" : "ecream.itim-cj.ro:2170",
"RO-15-NIPNE" : "tblb01.nipne.ro:2170",
"RO-16-UAIC" : "ce-grid.grid.uaic.ro:2170",
"ROC_Canada_SERVICES" : "roc-se.triumf.ca:2170",
"RRC-KI" : "gate.grid.kiae.ru:2170",
"RRC-KI-T1" : "taxer.t1.grid.kiae.ru:2170",
"RTUETF" : "ce01.grid.etf.rtu.lv:2170",
"RU-ISA-CGTDC" : "grid.isa.ru:2170",
"RU-Novosibirsk-BINP" : "lcg-bdii-001.inp.nsk.su:2170",
"RU-Phys-SPbSU" : "phys5.gridzone.ru:2170",
"RU-Protvino-IHEP" : "bdii0002.m45.ihep.su:2170",
"RU-SPbSU" : "alice23.spbu.ru:2170",
"RUG-CIT" : "columba.grid.rug.nl:2170",
"RWTH-Aachen" : "grid-mon.physik.rwth-aachen.de:2170",
"RedIRIS" : "site-bdii.rediris.es:2170",
"RedIRIS_GILDA" : "gilda-ce.rediris.es:2170",
"Ru-Troitsk-INR-LCG2" : "grinr09.inr.troitsk.ru:2170",
"SAMPA" : "sampabdii.if.usp.br:2170",
"SARA-LISA" : "mu9.matrix.sara.nl:2170",
"SARA-MATRIX" : "sitebdii.grid.sara.nl:2170",
"SCAI" : "glite-bdii.scai.fraunhofer.de:2170",
"SDU-LCG2" : "ce.grid.hepg.sdu.edu.cn:2170",
"SE-SNIC-T2" : "bdii-se-t2.ndgf.org:2170",
"SFU-LCG2" : "wormhole.westgrid.ca:2170",
"SGAI-CSIC" : "grid-glite-bdii-00.sgai.csic.es:2170",
"SISSA-Trieste" : "ce-01.grid.sissa.it:2170",
"SN-UCAD" : "bdii.cci.ucad.sn:2170",
"SNS-PISA" : "bdii.sns.it:2170",
"SOLEIL" : "grid-sbdii.synchrotron-soleil.fr:2170",
"spaci-lecce-ia64" : "ce2.egee.unile.it:2170",
"SPACI-NAPOLI-IA64" : "spaci01.na.infn.it:2170",
"SU-GRID" : "grid.su.lt:2170",
"SU-Protvino-IHEP" : "ce.ngc6475.ihep.su:2170",
"SUPERCOMPUTO-UNAM" : "gl02.super.unam.mx:2170",
"SZTAKI" : "fn1.hpcc.sztaki.hu:2170",
"ScotGRID-Edinburgh" : "ce.epcc.ed.ac.uk:2170",
"SiGNET" : "dodo.ijs.si:2170",
"T2-TH-CUNSTDA" : "curium.lsr.nectec.or.th:2170",
"T2_Estonia" : "bdii.hep.kbfi.ee:2170",
"T3_CH_PSI" : "t3bdii.psi.ch:2170",
"T3_HU_Debrecen" : "bdii.grid.atomki.hu:2170",
"TASK" : "ce.grid.task.gda.pl:2170",
"TAU-LCG2" : "lcfgng.cs.tau.ac.il:2170",
"TECHNION-HEP" : "tech-bdii.hep.technion.ac.il:2170",
"TECHNION-LCG2" : "ds-lcg-ce01.cs.technion.ac.il:2170",
"TH-HAII" : "ce.haii.or.th:2170",
"TH-NECTEC-LSR" : "lion.lsr.nectec.or.th:2170",
"TIFR-CMS" : "cms-ce.tifrgrid.res.in:2170",
"tifrlcg2" : "lcg2ce.tifrgrid.res.in:2135",
"TOKYO-LCG2" : "lcg-sitebdii.icepp.jp:2170",
"toronto-lcg2" : "bigmac-lcg-ce2.physics.utoronto.ca:2170",
"TR-01-ULAKBIM" : "ce.ulakbim.gov.tr:2170",
"TR-02-ATATURK" : "cn02.atauni.edu.tr:2170",
"TR-03-METU" : "cox01.grid.metu.edu.tr:2170",
"TR-04-ERCIYES" : "grid01.erciyes.edu.tr:2170",
"TR-05-BOUN" : "yildirim.grid.boun.edu.tr:2170",
"TR-08-CUKUROVA" : "grid01.cu.edu.tr:2170",
"TR-09-ITU" : "ituce.grid.itu.edu.tr:2170",
"TR-10-ULAKBIM" : "kalkan1.ulakbim.gov.tr:2170",
"TRIGRID-INFN-CATANIA" : "infn-wn-01.ct.trigrid.it:2170",
"TRIUMF-LCG2" : "site-bdii.triumf.ca:2170",
"TU-Kosice" : "mon.grid.tuke.sk:2170",
"TUDresden-ZIH" : "cleopatra.zih.tu-dresden.de:2170",
"TW-ASGC-CERT" : "lcg00006.grid.sinica.edu.tw:2170",
"TW-EMI-PPS" : "emi001.grid.sinica.edu.tw:2170",
"TW-FTT" : "f-sbdii.grid.sinica.edu.tw:2170",
"TW-NCHU-AAC-01" : "gridce.aac.nchu.edu.tw:2170",
"TW-NCUHEP" : "grid73.phy.ncu.edu.tw:2170",
"TW-NIU-EECS-01" : "niugce.grid.niu.edu.tw:2170",
"TW-NTCU-HPC-01" : "host001.hpc.ntcu.edu.tw:2170",
"TW-NTU-HEP" : "ntugrid2.phys.ntu.edu.tw:2170",
"TW-eScience" : "as-sbdii.euasiagrid.org:2170",
"Taiwan-IPAS-LCG2" : "atlasce.phys.sinica.edu.tw:2170",
"Taiwan-LCG2" : "w-bdii.grid.sinica.edu.tw:2170",
"Taiwan-NCUCC-LCG2" : "ce.cc.ncu.edu.tw:2170",
"Turing" : "turing.ttu.ee:2170",
"UA-BITP" : "ce.bitp.kiev.ua:2170",
"UA-IFBG" : "grid.ifbg.org.ua:2170",
"UA-IMBG" : "se.imbg.org.ua:2170",
"UA-IRE" : "bdii.ire.kharkov.ua:2170",
"UA-ISMA" : "gl-ce.isma.kharkov.ua:2170",
"UA-KNU" : "gris.univ.kiev.ua:2170",
"UA-MHI" : "arc.hpc-mhi.org:2170",
"UA-NSCMBR" : "se.biomed.kiev.ua:2170",
"UA-PIMEE" : "bdii.matmoden.kiev.ua:2170",
"UAM-LCG2" : "gridbdiisite.ft.uam.es:2170",
"UA_BITP_ARC" : "arc.bitp.kiev.ua:2170",
"UA_ICMP_ARC" : "west.icmp.lviv.ua:2170",
"UA_ICYB_ARC" : "uagrid.org.ua:2170",
"UA_ILTPE_ARC" : "ds4.ilt.kharkov.ua:2170",
"UB-LCG2" : "hep-bdii.ecm.ub.es:2170",
"UCL-CCC" : "ce-a.ccc.ucl.ac.uk:2170",
"UFL-LCG2" : "ufloridaigt.phys.ufl.edu:2170",
"UFRJ-IF" : "lnx114.eela.if.ufrj.br:2170",
"UIOWA-LCG2" : "lcg-mon.its.uiowa.edu:2170",
"UKI-LT2-Brunel" : "dc2-grid-69.brunel.ac.uk:2170",
"UKI-LT2-IC-HEP" : "bdii.grid.hep.ph.ic.ac.uk:2170",
"UKI-LT2-IC-HEP-PPS" : "imalaydee.hep.ph.ic.ac.uk:2170",
"UKI-LT2-IC-LeSC" : "site-bdii.lesc.doc.ic.ac.uk:2170",
"UKI-LT2-QMUL" : "bdii02.esc.qmul.ac.uk:2170",
"UKI-LT2-RHUL" : "sbdii2.ppgrid1.rhul.ac.uk:2170",
"UKI-LT2-UCL-CENTRAL" : "gw-1.ccc.ucl.ac.uk:2170",
"UKI-LT2-UCL-HEP" : "lcg-bdii01.hep.ucl.ac.uk:2170",
"UKI-NORTHGRID-LANCS-HEP" : "fal-pygrid-14.lancs.ac.uk:2170",
"UKI-NORTHGRID-LIV-HEP" : "hepgrid4.ph.liv.ac.uk:2170",
"UKI-NORTHGRID-MAN-HEP" : "site-bdii.tier2.hep.manchester.ac.uk:2170",
"UKI-NORTHGRID-SHEF-HEP" : "lcg.shef.ac.uk:2170",
"UKI-SCOTGRID-DURHAM" : "site-bdii.dur.scotgrid.ac.uk:2170",
"UKI-SCOTGRID-ECDF" : "info2.glite.ecdf.ed.ac.uk:2170",
"UKI-SCOTGRID-GLASGOW" : "svr030.gla.scotgrid.ac.uk:2170",
"UKI-SOUTHGRID-BHAM-HEP" : "epgr09.ph.bham.ac.uk:2170",
"UKI-SOUTHGRID-BHAM-PPS" : "epbf006.ph.bham.ac.uk:2170",
"UKI-SOUTHGRID-BRIS-HEP" : "lcgbdii.phy.bris.ac.uk:2170",
"UKI-SOUTHGRID-CAM-HEP" : "vserv08.hep.phy.cam.ac.uk:2170",
"UKI-SOUTHGRID-OX-HEP" : "t2bdii06.physics.ox.ac.uk:2170",
"UKI-SOUTHGRID-RALPP" : "site-bdii.pp.rl.ac.uk:2170",
"UKI-SOUTHGRID-RDG" : "ce1.acet.rdg.ac.uk:2170",
"UKI-SOUTHGRID-SUSX" : "grid-bdii.hpc.susx.ac.uk:2170",
"UKI-ScotGrid-Gla-PPS" : "grid06.ph.gla.ac.uk:2170",
"ULA-MERIDA" : "grid005.cecalc.ula.ve:2170",
"UMB-BB" : "sbdii.grid.umb.sk:2170",
"UMinho-CP" : "site-bdii.cp.di.uminho.pt:2170",
"UNI-BONN" : "grid-ce.physik.uni-bonn.de:2170",
"UNI-DORTMUND" : "udo-bdii01.grid.tu-dortmund.de:2170",
"UNI-FREIBURG" : "bdii.bfg.uni-freiburg.de:2170",
"UNI-KARLSRUHE" : "ic-bdii.scc.kit.edu:2170",
"UNI-PERUGIA" : "cex.grid.unipg.it:2170",
"UNI-SIEGEN-HEP" : "vgn001.hep.physik.uni-siegen.de:2170",
"UNIANDES" : "piaroa.uniandes.edu.co:2170",
"UNIBE-ID" : "nordugrid.unibe.ch:2135",
"UNIBE-LHEP" : "bdii.lhep.unibe.ch:2170",
"UNICAN" : "ce01.macc.unican.es:2170",
"UNICAN-IMATH" : "ce.macc.unican.es:2170",
"glue12" : "gateway03.dcsc.ku.dk:2135",
"UNIGE-DPNC" : "gridvm2.unige.ch:2170",
"UNINA-EGEE" : "sitebdii.scope.unina.it:2170",
"UNIV-LILLE" : "bdii.univ-lille1.fr:2170",
"UOGRID" : "cmgbdii.mieres.uniovi.es:2170",
"UPJS-Kosice" : "sbdii.grid.upjs.sk:2170",
"UPV-GRyCAP" : "ngiesbdii.i3m.upv.es:2170",
"UPorto" : "mon01.up.pt:2170",
"USC-LCG2" : "bdii-emi.igfae.usc.es:2170",
"USCMS-FNAL-WC1" : "is.grid.iu.edu:2180",
"UT_CS" : "pinguin.mt.ut.ee:2170",
"UiB" : "glite2.bccs.uib.no:2170",
"umontreal-lcg2" : "lcg-ce.lps.umontreal.ca:2170",
"VDU-IF-LCG2" : "vdupdc.vdu.lt:2170",
"VGTU-CREAM" : "ce1.grid.vgtu.lt:2170",
"VGTU-TEST-gLite" : "grid.vgtu.lt:2170",
"VGTU-gLite" : "sbdii.grid.vgtu.lt:2170",
"VN-HPCC-HUT-HN" : "ui.hut.vngrid.vinaren.vn:2170",
"VN-IFI" : "sbdii.ifi.vngrid.vinaren.vn:2170",
"VN-IFI-PPS" : "ce.ifi.vngrid.vinaren.vn:2170",
"VN-IOIT-DCNET" : "ce.dcnet.ioit-hcm.vngrid.org:2170",
"VN-IOIT-HN" : "ce.ioit.vngrid.vinaren.vn:2170",
"VN-IOIT-KEYLAB" : "ce.keylab.ioit-hcm.vngrid.org:2170",
"VU-MIF-LCG2" : "grid6.mif.vu.lt:2170",
"VU-MIF-TEST" : "grid2.mif.vu.lt:2170",
"WARSAW-EGEE" : "mon.polgrid.pl:2170",
"WCSS" : "ce.egee.wcss.wroc.pl:2170",
"WCSS-PPS" : "bdii.wcss.wroc.pl:2170",
"WCSS64" : "tatooine.wcss.pl:2170",
"WEIZMANN-LCG2" : "wipp-ce.weizmann.ac.il:2170",
"WUT" : "bdii.if.pw.edu.pl:2170",
"Wuhan" : "ce.grid.ccnu.edu.cn:2170",
"YerPhi" : "armgrid1.yerphi.am:2170",
"ZA-MERAKA" : "site-bdii.c4.csir.co.za:2170",
"ZA-UJ" : "glite-bdii.grid.uj.ac.za:2170",
"ZA-WITS-CORE" : "bdii.core.wits.ac.za:2170",
"ZIB" : "sbdii.zib.de:2170",
"e-ca-iaa" : "e-ce.iaa.es:2170",
"egee.fesb.hr" : "se.fesb.egi.cro-ngi.hr:2170",
"egee.irb.hr" : "se.irb.egi.cro-ngi.hr:2170",
"egee.man.poznan.pl" : "ce.egee.man.poznan.pl:2170",
"egee.srce.hr" : "se.srce.egi.cro-ngi.hr:2170",
"hp-bristol" : "lcg-01.hpl.hp.com:2170",
"ifae" : "site-bdii-ifae.pic.es:2170",
"mainzgrid" : "mgbdii.physik.uni-mainz.de:2170",
"manchester-ngs2" : "ngsinfo.grid-support.ac.uk:2135",
"NGI-CETA-CIEMAT" : "ce-sge-ngi.ceta-ciemat.es:2170",
"oxford-ngs2" : "bdii.ngs.ac.uk:2170",
"pic" : "site-bdii.pic.es:2170",
"prague_cesnet_lcg2" : "cream2.grid.cesnet.cz:2170",
"prague_cesnet_lcg2_cert" : " skurut16.cesnet.cz:2170",
"prague_cesnet_pps" : "skurut67-1.cesnet.cz:2170",
"prague_cesnet_pt" : "skurut67-4.cesnet.cz:2170",
"praguelcg2" : "sbdii.farm.particle.cz:2170",
"preprod.nikhef.nl" : "tbn11.nikhef.nl::2170",
"ral-ngs2" : "sitebdii.ngs.rl.ac.uk:2170",
"ral-scarf" : "sitebdii.ngs.rl.ac.uk:2170",
"ru-Chernogolovka-IPCP-LCG2" : "grid-ce.icp.ac.ru:2170",
"ru-Moscow-FIAN-LCG2" : "ce1.grid.lebedev.ru:2170",
"ru-Moscow-MEPHI-LCG2" : "lxfarm07.mephi.ru:2170",
"ru-Moscow-SINP-LCG2" : "lcg02.sinp.msu.ru:2170",
"ru-PNPI" : "cluster.pnpi.nw.ru:2170",
"scotgrid-gla" : "ce1-gla.scotgrid.ac.uk:2170",
"wuppertalprod" : "grid-bdii.physik.uni-wuppertal.de:2170"
}

wlcg_site_bdiis = {
"Australia-ATLAS": "agsite.atlas.unimelb.edu.au",
"BEgrid-ULB-VUB": "sitebdii.iihe.ac.be",
"BEIJING-LCG2": "lcg002.ihep.ac.cn",
"BelGrid-UCL": "ingrid.cism.ucl.ac.be",
"BUDAPEST": "grid147.kfki.hu",
"CA-MCGILL-CLUMEQ-T2": "site-bdii.clumeq.mcgill.ca",
"CA-SCINET-T2": "lcg-se3.scinet.utoronto.ca",
"CA-VICTORIA-WESTGRID-T2": "charon02.westgrid.ca",
"CBPF": "site-bdii.cat.cbpf.br",
"CERN-PROD" : "prod-bdii.cern.ch",
"CIEMAT-LCG2": "lcg03.ciemat.es",
"CSCS-LCG2": "sbdii02.lcg.cscs.ch",
"CYFRONET-LCG2": "sbdii.grid.cyf-kr.edu.pl",
"DESY-HH": "grid-giis1.desy.de",
"DESY-ZN": "lcg-giis1.ifh.de",
"EELA-UNLP": "ce01.unlp.edu.ar",
"EELA-UTFSM": "site.hpc.utfsm.cl",
"EFDA-JET": "grid005.jet.efda.org",
"FI_HIP_T2": "bdii.hip.fi",
"FMPhI-UNIBA": "lcgmonitor.dnp.fmph.uniba.sk",
"FZK-LCG2" : "giis-fzk.gridka.de",
"GoeGrid": "bdii.goegrid.gwdg.de",
"GR-07-UOI-HEPLAB": "grid03.physics.uoi.gr",
"GRIF": "grid14.lal.in2p3.fr",
"GSI-LCG2": "lcg-bdii.gsi.de",
"HEPHY-UIBK": "test-ui.uibk.ac.at",
"Hephy-Vienna": "bdii.oeaw.ac.at",
"ICM": "apel.grid.icm.edu.pl",
"IEPSAS-Kosice": "glmon-iep-grid.saske.sk",
"ifae": "sitebdii-ifae02.pic.es",
"IFCA-LCG2": "gridiis01.ifca.es",
"IFIC-LCG2": "bdii01.ific.uv.es",
"IL-TAU-HEP": "tau-bdii.hep.tau.ac.il",
"IN-DAE-VECC-02": "dcache-server.tier2-kol.res.in",
"IN2P3-CC": "cclcgip01.in2p3.fr",
"IN2P3-CC-T2": "cclcgip05.in2p3.fr",
"IN2P3-CPPM": "marbdii.in2p3.fr",
"IN2P3-IRES": "sbgbdii2.in2p3.fr",
"IN2P3-LAPP": "lapp-site01.in2p3.fr",
"IN2P3-LPC": "clrlcgsbdii.in2p3.fr",
"IN2P3-LPSC": "lpsc-bdii.in2p3.fr",
"IN2P3-SUBATECH": "nanlcg01.in2p3.fr",
"INDIACMS-TIFR": "apel.indiacms.res.in",
"INFN-BARI": "gridba2.ba.infn.it",
"INFN-CATANIA": "alifarm10.ct.infn.it",
"INFN-CNAF-LHCB": "sg01-lhcb-t2.cr.cnaf.infn.it",
"INFN-FRASCATI": "atlasbdii.lnf.infn.it",
"INFN-LNL-2": "t2-sbdii.lnl.infn.it",
"INFN-MILANO-ATLASC": "t2-bdii.mi.infn.it",
"INFN-NAPOLI-ATLAS": "atlas-bdii.na.infn.it",
"INFN-PISA": "gridbdii0.pi.infn.it",
"INFN-ROMA1": "atlas-bdii.roma1.infn.it",
"INFN-ROMA1-CMS": "cmsrm-bdii.roma1.infn.it",
"INFN-T1" : "sg01-lcg.cr.cnaf.infn.it",
"INFN-TORINO": "t2-bdii-01.to.infn.it",
"ITEP": "creamce1.itep.ru",
"JINR-LCG2": "lcgsite.jinr.ru",
"Kharkov-KIPT-LCG2": "cms-eth0-1.kipt.kharkov.ua",
"KR-KISTI-GCRT-01": "sbdii-gcrt1.sdfarm.kr",
"KR-KISTI-GSDC-01" : "sbdii-gsdc1.sdfarm.kr",
"LCG_KNU": "cluster51.knu.ac.kr",
"LIP-Coimbra": "grid003.gridc.lip.pt",
"LIP-Lisbon": "site-bdii.lip.pt",
"LRZ-LMU": "lcg-lrz-bdii.grid.lrz.de",
"MPPMU": "grid-bdii.rzg.mpg.de",
"NCBJ-CIS": "bdii.cis.gov.pl",
"NCG-INGRID-PT": "sbdii01.ncg.ingrid.pt",
"NCP-LCG2": "pcncp26.ncp.edu.pk",
"NDGF-T1" : "bdii.ndgf.org",
"NIHAM": "alice003.nipne.ro",
"NIKHEF-ELPROD" : "siteinfo03.nikhef.nl",
"NO-NORGRID-T2": "bdii-no-t2.ndgf.org",
"pic" : "site-bdii.pic.es",
"praguelcg2": "sbdii1.farm.particle.cz",
"PSNC": "bdii.reef.man.poznan.pl",
"RAL-LCG2" : "site-bdii.gridpp.rl.ac.uk",
"RO-02-NIPNE": "baaf01.nipne.ro",
"RO-07-NIPNE": "tbit01.nipne.ro",
"RO-11-NIPNE": "lhcb-ce.nipne.ro",
"RO-13-ISS": "grid04.spacescience.ro",
"RO-14-ITIM": "ecream.itim-cj.ro",
"RO-16-UAIC": "ce-grid.grid.uaic.ro",
"RRC-KI": "gate.grid.kiae.ru",
"ru-Moscow-FIAN-LCG2": "ce1.grid.lebedev.ru",
"ru-Moscow-SINP-LCG2": "lcg02.sinp.msu.ru",
"ru-PNPI": "cluster.pnpi.nw.ru",
"RU-Protvino-IHEP": "bdii0002.m45.ihep.su",
"RU-SPbSU": "alice23.spbu.ru",
"Ru-Troitsk-INR-LCG2": "grinr09.inr.troitsk.ru",
"RWTH-Aachen": "grid-mon.physik.rwth-aachen.de",
"SAMPA": "sampabdii.if.usp.br",
"SARA-MATRIX": "sitebdii.grid.sara.nl",
"SE-SNIC-T2": "bdii-se-t2.ndgf.org",
"SFU-LCG2": "wormhole.westgrid.ca",
"SiGNET": "dodo.ijs.si",
"T2-TH-ALICE-NSTDA": "uranium.lsr.nectec.or.th",
"T2_Estonia": "bdii.hep.kbfi.ee",
"Taiwan-LCG2" : "w-bdii.grid.sinica.edu.tw",
"TECHNION-HEP": "tech-bdii.hep.technion.ac.il",
"TOKYO-LCG2": "lcg-sitebdii01.icepp.jp",
"TR-03-METU": "cox01.grid.metu.edu.tr",
"TR-10-ULAKBIM": "kalkan1.ulakbim.gov.tr",
"TRIUMF-LCG2" : "site-bdii.triumf.ca",
"TW-FTT": "f-sbdii01.grid.sinica.edu.tw",
"UA-BITP": "ce.bitp.kiev.ua",
"UA-KNU": "gris.univ.kiev.ua",
"UAM-LCG2": "gridbdiisite.ft.uam.es",
"UB-LCG2": "hep-bdii.ecm.ub.es",
"UKI-LT2-Brunel": "dc2-grid-69.brunel.ac.uk",
"UKI-LT2-IC-HEP": "bdii.grid.hep.ph.ic.ac.uk",
"UKI-LT2-QMUL": "bdii02.esc.qmul.ac.uk",
"UKI-LT2-RHUL": "sbdii2.ppgrid1.rhul.ac.uk",
"UKI-LT2-UCL-HEP": "lcg-bdii01.hep.ucl.ac.uk",
"UKI-NORTHGRID-LANCS-HEP": "fal-pygrid-14.lancs.ac.uk",
"UKI-NORTHGRID-LIV-HEP": "hepgrid4.ph.liv.ac.uk",
"UKI-NORTHGRID-MAN-HEP": "site-bdii.tier2.hep.manchester.ac.uk",
"UKI-NORTHGRID-SHEF-HEP": "lcg.shef.ac.uk",
"UKI-SCOTGRID-DURHAM": "site-bdii.dur.scotgrid.ac.uk",
"UKI-SCOTGRID-ECDF": "info2.glite.ecdf.ed.ac.uk",
"UKI-SCOTGRID-GLASGOW": "svr030.gla.scotgrid.ac.uk",
"UKI-SOUTHGRID-BHAM-HEP": "epgr09.ph.bham.ac.uk",
"UKI-SOUTHGRID-BRIS-HEP": "lcgbdii.phy.bris.ac.uk",
"UKI-SOUTHGRID-CAM-HEP": "vserv08.hep.phy.cam.ac.uk",
"UKI-SOUTHGRID-OX-HEP": "t2bdii06.physics.ox.ac.uk",
"UKI-SOUTHGRID-RALPP": "heplnv140.pp.rl.ac.uk",
"UKI-SOUTHGRID-SUSX": "grid-bdii.hpc.susx.ac.uk",
"UNIANDES": "piaroa.uniandes.edu.co",
"UNIBE-LHEP": "dpm.lhep.unibe.ch",
"UNI-FREIBURG": "bdii.bfg.uni-freiburg.de",
"USC-LCG2": "bdii-emi.igfae.usc.es",
"WEIZMANN-LCG2": "wipp-ce.weizmann.ac.il",
"wuppertalprod": "grid-bdii.physik.uni-wuppertal.de"
}

lhcb_site_bdiis = {
"ARAGRID-CIENCIAS": "sbdiic-iber.bifi.unizar.es",
"AUVEGRID": "obssbdii.univ-bpclermont.fr",
"BG01-IPP": "sbdii.ipp.acad.bg",
"BIFI": "sbdii-egi.bifi.unizar.es",
"BMEGrid": "mon.hpc.iit.bme.hu",
"CBFP": "site-bdii.cat.cbpf.br",
"CERN-PROD" : "prod-bdii.cern.ch",
"CSCS-LCG2": "sbdii02.lcg.cscs.ch",
"CYFRONET-LCG2": "sbdii.grid.cyf-kr.edu.pl",
"DESY-HH": "grid-giis1.desy.de",
"EFDA-JET": "grid005.jet.efda.org",
"FZK-LCG2" : "giis-fzk.gridka.de",
"GR-04-FORTH-ICS": "grid001.ics.forth.gr",
"GRIF": "grid14.lal.in2p3.fr",
"GRISU-UNINA": "grisusitebdii.scope.unina.it",
"CY-01-KIMON": "sbdii.grid.ucy.ac.cy",
"ICM": "apel.grid.icm.edu.pl",
"IFJ-PAN-BG": "fwe02.ifj.edu.pl",
"IL-TAU-HEP": "tau-bdii.hep.tau.ac.il",
"IN2P3-CC": "cclcgip03.in2p3.fr",
"IN2P3-CC-T2": "cclcgip05.in2p3.fr",
"IN2P3-CPPM": "marbdii.in2p3.fr",
"IN2P3-LAPP": "lapp-site01.in2p3.fr",
"IN2P3-LPC": "clrlcgsbdii.in2p3.fr",
"INFN-BOLOGNA-T3": "sgbo-t3.cr.cnaf.infn.it",
"INFN-CATANIA": "alifarm10.ct.infn.it",
"INFN-CNAF-LHCB": "sg01-lhcb-t2.cr.cnaf.infn.it",
"INFN-FERRARA": "gridsite.fe.infn.it",
"INFN-FRASCATI": "atlasbdii.lnf.infn.it",
"INFN-LNL-2": "t2-sbdii.lnl.infn.it",
"INFN-MILANO-ATLASC": "t2-bdii.mi.infn.it",
"INFN-NAPOLI-ATLAS": "atlas-bdii.na.infn.it",
"INFN-PADOVA": "prod-bdii-02.pd.infn.it",
"INFN-PISA": "gridbdii0.pi.infn.it",
"INFN-ROMA2": "gridvm02.roma2.infn.it",
"INFN-T1" : "sg01-lcg.cr.cnaf.infn.it",
"INFN-TORINO": "t2-bdii-01.to.infn.it",
"INFN-TRIESTE": "gridbdii.ts.infn.it",
"ITEP": "creamce1.itep.ru",
"ITWM": "fornax-bdii.itwm.fhg.de",
"JINR-LCG2": "lcgsite.jinr.ru",
"NCBJ-CIS": "bdii.cis.gov.pl",
"NIKHEF-ELPROD" : "siteinfo03.nikhef.nl",
"PSNC": "bdii.reef.man.poznan.pl",
"RAL-LCG2" : "site-bdii.gridpp.rl.ac.uk",
"RO-07-NIPNE": "tbit01.nipne.ro",
"RO-11-NIPNE": "lhcb-ce.nipne.ro",
"RO-15-NIPNE": "tblb01.nipne.ro",
"RRC-KI": "gate.grid.kiae.ru",
"RRC-KI-T1": "taxer.t1.grid.kiae.ru",
"RU-Protvino-IHEP": "bdii0002.m45.ihep.su",
"RU-SPbSU": "alice23.spbu.ru",
"RUG-CIT": "columba.grid.rug.nl",
"Ru-Troitsk-INR-LCG2": "grinr09.inr.troitsk.ru",
"SARA-MATRIX": "sitebdii.grid.sara.nl",
"SNS-PISA": "bdii.sns.it",
"TECHNION-HEP": "tech-bdii.hep.technion.ac.il",
"UB-LCG2": "hep-bdii.ecm.ub.es",
"UKI-LT2-Brunel": "dc2-grid-69.brunel.ac.uk",
"UKI-LT2-IC-HEP": "bdii.grid.hep.ph.ic.ac.uk",
"UKI-LT2-QMUL": "bdii02.esc.qmul.ac.uk",
"UKI-LT2-RHUL": "sbdii2.ppgrid1.rhul.ac.uk",
"UKI-NORTHGRID-LANCS-HEP": "fal-pygrid-14.lancs.ac.uk",
"UKI-NORTHGRID-LIV-HEP": "hepgrid4.ph.liv.ac.uk",
"UKI-NORTHGRID-MAN-HEP": "site-bdii.tier2.hep.manchester.ac.uk",
"UKI-NORTHGRID-SHEF-HEP": "lcg.shef.ac.uk",
"UKI-SCOTGRID-DURHAM": "site-bdii.dur.scotgrid.ac.uk",
"UKI-SCOTGRID-ECDF": "info2.glite.ecdf.ed.ac.uk",
"UKI-SCOTGRID-GLASGOW": "svr030.gla.scotgrid.ac.uk",
"UKI-SOUTHGRID-BHAM-HEP": "epgr09.ph.bham.ac.uk",
"UKI-SOUTHGRID-BRIS-HEP": "lcgbdii.phy.bris.ac.uk",
"UKI-SOUTHGRID-CAM-HEP": "vserv08.hep.phy.cam.ac.uk",
"UKI-SOUTHGRID-OX-HEP": "t2bdii06.physics.ox.ac.uk",
"UKI-SOUTHGRID-RALPP": "heplnv140.pp.rl.ac.uk",
"UNI-DORTMUND": "udo-bdii01.grid.tu-dortmund.de",
"UNINA-EGEE": "sitebdii.scope.unina.it",
"USC-LCG2": "bdii-emi.igfae.usc.es",
"WCSS64": "tatooine.wcss.pl",
"WEIZMANN-LCG2": "wipp-ce.weizmann.ac.il",
"pic": "site-bdii.pic.es",
"ru-Moscow-SINP-LCG2": "lcg02.sinp.msu.ru",
"ru-PNPI": "cluster.pnpi.nw.ru"
}

lhcb_names_dict = {
"ARAGRID-CIENCIAS": "LCG.ARAGRID-CIENCIAS.es",
"AUVEGRID": "LCG.AUVER.fr",
"BG01-IPP": "LCG.IPP.bg",
"BIFI": "LCG.BIFI.es",
"BMEGrid": "LCG.BMEGrid.hu",
"CBFP": "LCG.CBPF.br",
"CERN-PROD" : "LCG.CERN.ch",
"CSCS-LCG2": "LCG.CSCS.ch",
"CY-01-KIMON": "LCG.KIMON.cy",
"CYFRONET-LCG2": "LCG.Krakow.pl",
"DESY-HH": "LCG.DESY.de",
"EFDA-JET": "LCG.EFDA.uk",
"FZK-LCG2" : "LCG.GRIDKA.de",
"GR-04-FORTH-ICS": "LCG.GR-04.gr",
"GRIF": "LCG.LAL.fr",
"GRISU-UNINA": "LCG.GRISU-UNINA.it",
"ICM": "LCG.ICM.pl",
"IFJ-PAN-BG": "LCG.IFJ-PAN.pl",
"IL-TAU-HEP": "LCG.TAU.il",
"IN2P3-CC": "LCG.IN2P3.fr",
"IN2P3-CC-T2": "LCG.IN2P3-T2.fr",
"IN2P3-CPPM": "LCG.CPPM.fr",
"IN2P3-LAPP": "LCG.LAPP.fr",
"IN2P3-LPC": "LCG.LPC.fr",
"INFN-BOLOGNA-T3": "LCG.Bologna.it",
"INFN-CATANIA": "LCG.Catania.it",
"INFN-CNAF-LHCB": "LCG.CNAF-T2.it",
"INFN-FERRARA": "LCG.Ferrara.it",
"INFN-FRASCATI": "LCG.Frascati.it",
"INFN-LNL-2": "LCG.Legnaro.it",
"INFN-MILANO-ATLASC": "LCG.MILANO-ATLASC.it",
"INFN-NAPOLI-ATLAS": "LCG.NAPOLI-ATLAS.it",
"INFN-PADOVA": "LCG.Padova.it",
"INFN-PISA": "LCG.Pisa.it",
"INFN-ROMA2": "LCG.Roma.it",
"INFN-T1" : "LCG.CNAF.it",
"INFN-TORINO": "LCG.Torino.it",
"INFN-TRIESTE": "LCG.Trieste.it",
"ITEP": "LCG.ITEP.ru",
"ITWM": "LCG.ITWM.de",
"JINR-LCG2": "LCG.JINR.ru",
"NCBJ-CIS": "LCG.NCBJ.pl",
"NIKHEF-ELPROD" : "LCG.NIKHEF.nl",
"PSNC": "LCG.PSNC.pl",
"RAL-LCG2" : "LCG.RAL.uk",
"RO-07-NIPNE": "LCG.NIPNE-07.ro",
"RO-11-NIPNE": "LCG.NIPNE-11.ro",
"RO-15-NIPNE": "LCG.NIPNE-15.ro",
"RRC-KI": "LCG.KIAE.ru",
"RRC-KI-T1": "LCG.RRCKI.ru",
"RU-Protvino-IHEP": "LCG.IHEP.su",
"RU-SPbSU": "LCG.SPBU.ru",
"RUG-CIT": "LCG.RUG.nl",
"Ru-Troitsk-INR-LCG2": "LCG.INR.ru",
"SARA-MATRIX": "LCG.SARA.nl",
"SNS-PISA": "LCG.SNS-PISA.it",
"TECHNION-HEP": "LCG.Haifa.il",
"UB-LCG2": "LCG.Barcelona.es",
"UKI-LT2-Brunel": "LCG.UKI-LT2-Brunel.uk",
"UKI-LT2-IC-HEP": "LCG.UKI-LT2-IC-HEP.uk",
"UKI-LT2-QMUL": "LCG.UKI-LT2-QMUL.uk",
"UKI-LT2-RHUL": "LCG.UKI-LT2-RHUL.uk",
"UKI-NORTHGRID-LANCS-HEP": "LCG.Lancashire.uk",
"UKI-NORTHGRID-LIV-HEP": "LCG.Liverpool.uk",
"UKI-NORTHGRID-MAN-HEP": "LCG.Manchester.uk",
"UKI-NORTHGRID-SHEF-HEP": "LCG.Sheffield.uk",
"UKI-SCOTGRID-DURHAM": "LCG.Durham.uk",
"UKI-SCOTGRID-ECDF": "LCG.ECDF.uk",
"UKI-SCOTGRID-GLASGOW": "LCG.Glasgow.uk",
"UKI-SOUTHGRID-BHAM-HEP": "LCG.BHAM-HEP.uk",
"UKI-SOUTHGRID-BRIS-HEP": "LCG.Bristol.uk",
"UKI-SOUTHGRID-CAM-HEP": "LCG.Cambridge.uk",
"UKI-SOUTHGRID-OX-HEP": "LCG.Oxford.uk",
"UKI-SOUTHGRID-RALPP": "LCG.RAL-HEP.uk",
"UNI-DORTMUND": "LCG.Dortmund.de",
"UNINA-EGEE": "LCG.UNINA.it",
"USC-LCG2": "LCG.USC.es",
"WCSS64": "LCG.WCSS.pl",
"WEIZMANN-LCG2": "LCG.WEIZMANN.il",
"pic": "LCG.PIC.es",
"ru-Moscow-SINP-LCG2": "LCG.SINP.ru",
"ru-PNPI": "LCG.PNPI.ru"
}

cms_site_bdiis= {
"BEgrid-ULB-VUB" : "sitebdii.iihe.ac.be:2170",
"BEIJING-LCG2" : "lcg002.ihep.ac.cn:2170",
"BelGrid-UCL" : "ingrid.cism.ucl.ac.be:2170",
"BUDAPEST" : "grid147.kfki.hu:2170",
"BY-NCPHEP" : "mirror.hep.by:2170",
"CERN-PROD" : "prod-bdii.cern.ch:2170",
"CIEMAT-LCG2" : "lcg03.ciemat.es:2170",
"CN-BEIJING-PKU" : "grid04.phy.pku.edu.cn:2170",
"CSCS-LCG2" : "bdii.lcg.cscs.ch:2170",
"DESY-HH" : "grid-giis.desy.de:2170",
"egee.irb.hr" : "se.irb.egi.cro-ngi.hr:2170",
"FI_HIP_T2" : "bdii.hip.fi:2170",
"FZK-LCG2" : "giis-fzk.gridka.de:2170",
"GR-05-DEMOKRITOS" : "arxiloxos1.inp.demokritos.gr:2170",
"GR-06-IASA" : "site-bdii02.marie.hellasgrid.gr:2170",
"GR-07-UOI-HEPLAB" : "grid03.physics.uoi.gr:2170",
"GRIF" : "bdii.grif.fr:2170",
"Hephy-Vienna" : "bdii.oeaw.ac.at:2170",
"HG-02-IASA" : "site-bdii01.marie.hellasgrid.gr:2170",
"ICM" : "apel.grid.icm.edu.pl:2170",
"IFCA-LCG2" : "gridiis01.ifca.es:2170",
"IN2P3-CC" : "cclcgip01.in2p3.fr:2170",
"IN2P3-CC-T2" : "cclcgip03.in2p3.fr:2170",
"IN2P3-IPNL" : "lyobdii.in2p3.fr:2170",
"IN2P3-IRES" : "sbgbdii1.in2p3.fr:2170",
"INDIACMS-TIFR" : "apel.indiacms.res.in:2170",
"INFN-BARI" : "gridba2.ba.infn.it:2170",
"INFN-BOLOGNA-T3" : "sgbo-t3.cr.cnaf.infn.it:2170",
"INFN-FIRENZE" : "grid001.fi.infn.it:2170",
"INFN-LNL-2" : "t2-sbdii.lnl.infn.it:2170",
"INFN-MIB" : "bdii.mib.infn.it:2170",
"INFN-NAPOLI-CMS" : "cmsce01.na.infn.it:2170",
"INFN-PERUGIA" : "cream-bdii.pg.infn.it:2170",
"INFN-PISA" : "gridbdii0.pi.infn.it:2170",
"INFN-ROMA1-CMS" : "cmsrm-bdii.roma1.infn.it:2170",
"INFN-T1" : "sg01-lcg.cr.cnaf.infn.it:2170",
"INFN-TRIESTE" : "gridbdii.ts.infn.it:2170",
"IR-IPM-HEP" : "bdii.particles.ipm.ac.ir:2170",
"ITEP" : "creamce1.itep.ru:2170",
"JINR-LCG2" : "lcgsite.jinr.ru:2170",
"JINR-T1" : "site.jinr-t1.ru:2170",
"Kharkov-KIPT-LCG2" : "cms-eth0-1.kipt.kharkov.ua:2170",
"KR-KNU-T3" : "cluster117.knu.ac.kr:2170",
"LCG_KNU" : "cluster51.knu.ac.kr:2170",
"MY-UPM-BIRUNI-01" : "is.biruni.upm.my:2170",
"NCG-INGRID-PT" : "sbdii01.ncg.ingrid.pt:2170",
"NCP-LCG2" : "pcncp26.ncp.edu.pk:2170",
"NZ-UOA" : "glite-bdii.ceres.auckland.ac.nz:2170",
"pic" : "site-bdii.pic.es:2170",
"RAL-LCG2" : "site-bdii.gridpp.rl.ac.uk:2170",
"RRC-KI" : "gate.grid.kiae.ru:2170",
"ru-Moscow-FIAN-LCG2" : "ce1.grid.lebedev.ru:2170",
"ru-Moscow-SINP-LCG2" : "lcg02.sinp.msu.ru:2170",
"ru-PNPI" : "cluster.pnpi.nw.ru:2170",
"RU-Protvino-IHEP" : "bdii0002.m45.ihep.su:2170",
"Ru-Troitsk-INR-LCG2" : "grinr09.inr.troitsk.ru:2170",
"RWTH-Aachen" : "grid-mon.physik.rwth-aachen.de:2170",
"T2_Estonia" : "bdii.hep.kbfi.ee:2170",
"T2-TH-CUNSTDA" : "curium.lsr.nectec.or.th:2170",
"T3_CH_PSI" : "t3bdii.psi.ch:2170",
"Taiwan-LCG2" : "w-bdii.grid.sinica.edu.tw:2170",
"TR-03-METU" : "cox01.grid.metu.edu.tr:2170",
"TW-FTT" : "f-sbdii.grid.sinica.edu.tw:2170",
"TW-NCUHEP" : "grid73.phy.ncu.edu.tw:2170",
"TW-NTU-HEP" : "ntugrid2.phys.ntu.edu.tw:2170",
"UKI-LT2-Brunel" : "dc2-grid-69.brunel.ac.uk:2170",
"UKI-LT2-IC-HEP" : "bdii.grid.hep.ph.ic.ac.uk:2170",
"UKI-LT2-QMUL" : "bdii02.esc.qmul.ac.uk:2170",
"UKI-LT2-RHUL" : "sbdii2.ppgrid1.rhul.ac.uk:2170",
"UKI-LT2-UCL-HEP" : "lcg-bdii01.hep.ucl.ac.uk:2170",
"UKI-SCOTGRID-ECDF" : "info2.glite.ecdf.ed.ac.uk:2170",
"UKI-SCOTGRID-GLASGOW" : "svr030.gla.scotgrid.ac.uk:2170",
"UKI-SOUTHGRID-BRIS-HEP" : "lcgbdii.phy.bris.ac.uk:2170",
"UKI-SOUTHGRID-OX-HEP" : "t2bdii06.physics.ox.ac.uk:2170",
"UKI-SOUTHGRID-RALPP" : "site-bdii.pp.rl.ac.uk:2170",
"UNIANDES" : "piaroa.uniandes.edu.co:2170",
"UOGRID" : "cmgbdii.mieres.uniovi.es:2170",
"USCMS-FNAL-WC1" : "is.grid.iu.edu:2180"
}

cms_names_dict = {
"Baylor-Tier3": "T3_US_Baylor",
"BEgrid-ULB-VUB": "T2_BE_IIHE",
"BEIJING-LCG2": "T2_CN_Beijing",
"BelGrid-UCL": "T2_BE_UCL",
"brown-cms-new": "T3_US_Brown",
"BUDAPEST": "T2_HU_Budapest",
"BY-NCPHEP": "T3_BY_NCPHEP",
"CERN-PROD-AI": "T2_CH_CERN_AI",
"CERN-PROD-HLT": "T2_CH_CERN_HLT",
"CERN-PROD": "T0_CH_CERN",
"CERN-PROD": "T1_CH_CERN",
"CERN-PROD": "T2_CH_CERN",
"CIEMAT-LCG2": "T2_ES_CIEMAT",
"cinvestav": "T3_MX_Cinvestav",
"CIT_CMS_T2": "T2_US_Caltech",
"CN-BEIJING-PKU": "T3_CN_PKU",
"CSCS-LCG2": "T2_CH_CSCS",
"DESY-HH": "T2_DE_DESY",
"egee.irb.hr": "T3_HR_IRB",
"FI_HIP_T2": "T2_FI_HIP",
"Firefly": "T3_US_Omaha",
"FIUPG": "T3_US_FIU",
"FLTECH": "T3_US_FIT",
"FSU-HEP": "T3_US_FSU",
"FZK-LCG2": "T1_DE_KIT",
"GLOW": "T2_US_Wisconsin",
"GR-05-DEMOKRITOS": "T3_GR_Demokritos",
"GR-06-IASA": "T3_GR_IASA",
"GR-07-UOI-HEPLAB": "T2_GR_Ioannina",
"grid.puhep.res.in": "T3_IN_PUHEP",
"GRIF": "T2_FR_GRIF_LLR",
"GROW-PROD": "T3_US_UIowa",
"Hephy-Vienna": "T2_AT_Vienna",
"HG-02-IASA": "T3_GR_IASA",
"ICM": "T2_PL_Warsaw",
"IFCA-LCG2": "T2_ES_IFCA",
"IFRU": "T2_FR_GRIF_IRFU",
"IN2P3-CC": "T1_FR_CCIN2P3",
"IN2P3-CC-T2": "T2_FR_CCIN2P3",
"IN2P3-IPNL": "T3_FR_IPNL",
"IN2P3-IRES": "T2_FR_IPHC",
"INDIACMS-TIFR": "T2_IN_TIFR",
"INFN-BARI": "T2_IT_Bari",
"INFN-BOLOGNA-T3": "T3_IT_Bologna",
"INFN-FIRENZE": "T3_IT_Firenze",
"INFN-LNL-2": "T2_IT_Legnaro",
"INFN-MIB": "T3_IT_MIB",
"INFN-NAPOLI-CMS": "T3_IT_Napoli",
"INFN-PERUGIA": "T3_IT_Perugia",
"INFN-PISA": "T2_IT_Pisa",
"INFN-ROMA1-CMS": "T2_IT_Rome",
"INFN-T1": "T1_IT_CNAF",
"INFN-TRIESTE": "T3_IT_Trieste",
"IR-IPM-HEP": "T3_IR_IPM",
"ITEP": "T2_RU_ITEP",
"JINR-LCG2": "T2_RU_JINR",
"JINR-T1-DISK": "T1_RU_JINR_Disk",
"JINR-T1": "T1_RU_JINR",
"Kharkov-KIPT-LCG2": "T2_UA_KIPT",
"KR-KNU-T3": "T3_KR_KNU",
"KR_UOS_SSCC": "T3_KR_UOS",
"LCG_KNU": "T2_KR_KNU",
"MIT_CMS": "T2_US_MIT",
"MIT_CMS_T3": "T3_US_MIT",
"MY-UPM-BIRUNI-01": "T2_MY_UPM_BIRUNI",
"NCG-INGRID-PT": "T2_PT_NCG_Lisbon",
"NCP-LCG2": "T2_PK_NCP",
"Nebraska": "T2_US_Nebraska",
"NU Tier3": "T3_US_NU",
"NWICG_NDCMS": "T3_US_NotreDame",
"NYSGRID-CCR-U2": "T3_US_UB",
"NYSGRID_CORNELL_NYS1": "T3_US_Cornell",
"NZ-UOA": "T3_NZ_UOA",
"osu-cms": "T3_US_OSU",
"pic": "T1_ES_PIC",
"Princeton": "T3_US_Princeton",
"Purdue-Carter": "T2_US_Purdue",
"Purdue-Conte": "T2_US_Purdue",
"Purdue-Hansen": "T2_US_Purdue",
"Purdue-RCAC": "T2_US_Purdue",
"Purdue-Rossmann": "T2_US_Purdue",
"RAL-LCG2-DISK": "T1_UK_RAL_Disk",
"RAL-LCG2": "T1_UK_RAL",
"Rice": "T3_US_Rice",
"RRC-KI": "T2_RU_RRC_KI",
"ru-Moscow-FIAN-LCG2": "T3_RU_FIAN",
"ru-Moscow-SINP-LCG2": "T2_RU_SINP",
"ru-PNPI": "T2_RU_PNPI",
"RU-Protvino-IHEP": "T2_RU_IHEP",
"rutgers-cms": "T3_US_Rutgers",
"Ru-Troitsk-INR-LCG2": "T2_RU_INR",
"RWTH-Aachen": "T2_DE_RWTH",
"SPRACE": "T2_BR_SPRACE",
"T2_Estonia": "T2_EE_Estonia",
"T2-TH-CUNSTDA": "T2_TH_CUNSTDA",
"t3asparrot": "T3_AS_Parrot",
"T3_CH_PSI": "T3_CH_PSI",
"t3euparrot": "T3_EU_Parrot",
"T3_US_JHU": "T3_US_JHU",
"T3_US_Kansas": "T3_US_Kansas",
"t3usparrot": "T3_US_Parrot",
"t3usparrottest": "T3_US_ParrotTest",
"T3_US_Princeton_ICSE": "T3_US_Princeton_ICSE",
"T3_US_UTENN": "T3_US_UTENN",
"Taiwan-LCG2": "T1_TW_ASGC",
"TAMU_BRAZOS": "T3_US_TAMU",
"TR-03-METU": "T2_TR_METU",
"ttu-antaeus": "T3_US_TTU",
"TW-FTT": "T2_TW_Taiwan",
"TW-NCUHEP": "T3_TW_NCU",
"TW-NTU-HEP": "T3_TW_NTU_HEP",
"UCD": "T3_US_UCD",
"UColorado_HEP": "T3_US_Colorado",
"UCR-HEP": "T3_US_UCR",
"UCSDT2-B": "T2_US_UCSD",
"UCSDT2": "T2_US_UCSD",
"UERJ": "T2_BR_UERJ",
"UFlorida-HPC": "T2_US_Florida",
"UKI-LT2-Brunel": "T2_UK_London_Brunel",
"UKI-LT2-IC-HEP": "T2_UK_London_IC",
"UKI-LT2-QMUL": "T3_UK_London_QMUL",
"UKI-LT2-RHUL": "T3_UK_London_RHUL",
"UKI-LT2-UCL-HEP": "T3_UK_London_UCL",
"UKI-SCOTGRID-ECDF": "T3_UK_ScotGrid_ECDF",
"UKI-SCOTGRID-GLASGOW": "T3_UK_ScotGrid_GLA",
"UKI-SOUTHGRID-BRIS-HEP": "T2_UK_SGrid_Bristol",
"UKI-SOUTHGRID-OX-HEP": "T3_UK_SGrid_Oxford",
"UKI-SOUTHGRID-RALPP": "T2_UK_SGrid_RALPP",
"umd-cms": "T3_US_UMD",
"UMissHEP": "T3_US_UMiss",
"UMN-CMS": "T3_US_Minnesota",
"UNIANDES": "T3_CO_Uniandes",
"UOGRID": "T3_ES_Oviedo",
"uprm-cms": "T3_US_PuertoRico",
"USCMS-FNAL-LPC": "T3_US_FNALLPC",
"USCMS-FNAL-WC1-DISK": "T1_US_FNAL_Disk",
"USCMS-FNAL-WC1": "T1_US_FNAL",
"USCMS-FNAL-XEN": "T3_US_FNALXEN",
"UVA-HEP": "T3_US_UVA",
"Vanderbilt_EC2": "T3_US_Vanderbilt_EC2",
"Vanderbilt": "T2_US_Vanderbilt"
}
