schema = {
    'GlueSite' : {
        'GlueSiteUniqueID' : ('ID', True, True),
        'GlueSiteName' : ( 'String', True, False),
        'GlueSiteDescription' : ( 'String', True, True),
        'GlueSiteEmailContact' : ( 'Email_t', True, False),
        'GlueSiteUserSupportContact' : ( 'Email_t', True, False),
        'GlueSiteSysAdminContact' : ( 'Email_t', True, False),
        'GlueSiteSecurityContact' : ( 'Email_t', True, False),
        'GlueSiteLocation' : ( 'String', True, True),
        'GlueSiteLatitude' : ( 'Real32', True, True),
        'GlueSiteLongitude' : ( 'Real32', True, True),
        'GlueSiteWeb' : ( 'URL', True, True),
        'GlueSiteSponsor' : ( 'String', False, False),
        'GlueSiteOtherInfo' : ( 'String', False, False),
        },
    'GlueService' : {
        'GlueServiceUniqueID' : ('ID', True, True),
        'GlueServiceName' : ( 'String', True, True),
        'GlueServiceType' : ( 'ServiceType_t', True, True),
        'GlueServiceVersion' : ( 'String', True, True),
        'GlueServiceEndpoint' : ( 'URL', True, True),
        'GlueServiceStatus' : ( 'String', True, True),
        'GlueServiceStatusInfo' : ( 'String', True, True),
        'GlueServiceWSDL' : ( 'String', True, True),
        'GlueServiceSemantics' : ( 'URL', True, True),
        'GlueServiceStartTime' : ( 'DateTime_t', True, True),
        'GlueServiceOwner' : ( 'String', False, True),
        'GlueServiceAccessControlBaseRule' : ( 'ACBR_t', False, True),
        }, 
    'GlueServiceData' : {
        'GlueServiceKey' : ( 'String', True, True),
        'GlueServiceValue' : ( 'String', True, True),
        },
    'GlueCluster' : {
        'GlueClusterUniqueID' : ('ID', True, True),
        'GlueClusterName' : ( 'String', True, True),
        'GlueClusterTmpDir' : ( 'String', True, True),
        'GlueClusterWNTmpDir' : ( 'String', True, True),
        },
    'GlueCE' : {
        'GlueCEUniqueID' : ('ID', True, True),
        'GlueCEName' : ( 'String', True, True),
        'GlueCEImplementationName' : ( 'String', True, True),
        'GlueCEImplementationVersion' : ( 'String', True, True),
        'GlueCECapability' : ( 'String', False, True),
        },
    'GlueCEInfo' : {
        'GlueCEInfoLRMSType' : ( 'lrms_t', True, True),
        'GlueCEInfoLRMSVersion' : ( 'String', True, True),
        'GlueCEInfoGRAMVersion' : ( 'String', True, True),
        'GlueCEInfoHostName' : ( 'String', True, True),
        'GlueCEInfoGatekeeperPort' : ( 'Int32', True, True),
        'GlueCEInfoJobManager' : ( 'String', True, True),
        'GlueCEInfoContactString' : ( 'String', True, True),
        'GlueCEInfoTotalCPUs' : ( 'Int32', True, True),
        'GlueCEInfoApplicationDir' : ( 'String', True, True),
        'GlueCEInfoDataDir' : ( 'String', True, True),
        'GlueCEInfoDefaultSE' : ( 'String', True, True),
        },
    'GlueCEState' : {
        'GlueCEStateRunningJobs' : ( 'Int32', True, True),
        'GlueCEStateWaitingJobs' : ( 'Int32', True, True),
        'GlueCEStateTotalJobs' : ( 'Int32', True, True),
        'GlueCEStateEstimatedResponseTime' : ( 'Int32', True, True),
        'GlueCEStateWorstResponseTime' : ( 'Int32', True, True),
        'GlueCEStateFreeJobSlots' : ( 'Int32', True, True),
        'GlueCEStateFreeCPUs' : ( 'Int32', True, True),
        'GlueCEStateStatus' : ( 'String', True, True),
        },
    'GlueCEPolicy' : {
        'GlueCEPolicyMaxWallClockTime' : ( 'Int32', True, True),
        'GlueCEPolicyMaxObtainableWallClockTime' : ( 'Int32', True, True),
        'GlueCEPolicyMaxCPUTime' : ( 'Int32', True, True),
        'GlueCEPolicyMaxObtainableCPUTime' : ( 'Int32', True, True),
        'GlueCEPolicyMaxTotalJobs' : ( 'Int32', True, True),
        'GlueCEPolicyMaxRunningJobs' : ( 'Int32', True, True),
        'GlueCEPolicyMaxWaitingJobs' : ( 'Int32', True, True),
        'GlueCEPolicyPriority' : ( 'Int32', True, True),
        'GlueCEPolicyAssignedJobSlots' : ( 'Int32', True, True),
        'GlueCEPolicyMaxSlotsPerJobs' : ( 'Int32', True, True),
        'GlueCEPolicyPreemption' : ( 'Boolean', True, True),
        },
    'GlueCEAccessControlBase' : {
        'GlueCEAccessControlBaseRule' : ( 'ACBR_t', False, True),
        },
    'GlueVOView' : {
        'GlueVOViewLocalID' : ('ID', True, True),
        },
    'GlueSubCluster' : {
        'GlueSubClusterUniqueID' : ('ID', True, True),
        'GlueSubClusterName' : ( 'String', True, True),
        'GlueSubClusterPhysicalCPUs' : ( 'Int32', True, True),
        'GlueSubClusterLogicalCPUs' : ( 'Int32', True, True),
        },
    'GlueHost' : {
        'GlueHostProperty' : ( 'String', True, True),
        },
    'GlueHostOperatingSystem' : {
        'GlueHostOperatingSystemName' : ( 'String', True, True),
        'GlueHostOperatingSystemRelease' : ( 'String', True, True),
        'GlueHostOperatingSystemVersion' : ( 'String', True, True),
        },
    'GlueHostProcessor' : {
        'GlueHostProcessorModel' : ( 'String', True, True),
        'GlueHostProcessorVersion' : ( 'String', True, True),
        'GlueHostProcessorVendor' : ( 'String', True, True),
        'GlueHostProcessorClockSpeed' : ( 'Int32', True, True),
        'GlueHostProcessorInstructionSet' : ( 'String', True, True),
        'GlueHostProcessorOtherDescription' : ( 'String', True, True),
        },
    'GlueHostMainMemory' : {
        'GlueHostMainMemoryRAMSize' : ( 'Int32', True, True),
        'GlueHostMainMemoryVirtualSize' : ( 'Int32', True, True),
        },
    'GlueHostNetworkAdapter' : {
        'GlueHostNetworkAdapterOutboundIP' : ( 'Boolean', True, True),
        'GlueHostNetworkAdapterInboundIP' : ( 'Boolean', True, True),
        },
    'GlueHostArchitecture' : {
        'GlueHostArchitecturePlatformType' : ( 'String', True, True),
        'GlueHostArchitectureSMPSize' : ( 'Int32', True, True),
        },
    'GlueHostBenchmark' : {
        'GlueHostBenchmarkSI00' : ( 'Int32', True, True),
        'GlueHostBenchmarkSF00' : ( 'Int32', True, True),
        },
    'GlueHostApplicationSoftware' : { 
        'GlueHostApplicationSoftwareRunTimeEnvironment' : ( 'String', True, True),
        },
    'GlueSE' : {
        'GlueSEUniqueID' : ( 'String', True, True),
        'GlueSEName' : ( 'String', True, True),
        'GlueSEArchitecture' : ( 'SEArch_t', True, True),
        'GlueSESizeTotal' : ( 'Int32', True, True),
        'GlueSESizeFree' : ( 'Int32', True, True),
        'GlueSEPort' : ( 'Int32', True, True),
        'GlueSEStateCurrentIOLoad' : ( 'String', True, True),
        'GlueSEImplementationName' : ( 'SSImpl_t', True, True),
        'GlueSEImplementationVersion' : ( 'String', True, True),
        'GlueSEStatus' : ( 'SEStatus_t', True, True),
        'GlueSETotalOnlineSize' : ( 'Int32', True, True),
        'GlueSETotalNearlineSize' : ( 'Int32', True, True),
        'GlueSEUsedOnlineSize' : ( 'Int32', True, True),
        'GlueSEUsedNearlineSize' : ( 'Int32', True, True),
        },
    'GlueSA' : {
    'GlueSALocalID' : ( 'ID', True, True),
    'GlueSARoot' : ( 'String', True, True),
    'GlueSAPath' : ( 'String', True, True),
    'GlueSAType' : ( 'SAType_t', True, True),
    'GlueSAAccessControlBase.Rule' : ( 'ACBR_t', True, True),
    'GlueSAName' : ( 'String', True, True),
    'GlueSATotalOnlineSize' : ( 'Int32', True, True),
    'GlueSAUsedOnlineSize' : ( 'Int32', True, True),
    'GlueSAFreeOnlineSize' : ( 'Int32', True, True),
    'GlueSAReservedOnlineSize' : ( 'Int32', True, True),
    'GlueSATotalNearlineSize' : ( 'Int32', True, True),
    'GlueSAUsedNearlineSize' : ( 'Int32', True, True),
    'GlueSAFreeNearlineSize' : ( 'Int32', True, True),
    'GlueSAReservedNearlineSize' : ( 'Int32', True, True),
    'GlueSARetentionPolicy' : ( 'RetentionPolicy_t', True, True),
    'GlueSAAccessLatency' : ( 'AccessLatency_t', True, True),
    'GlueSAExpirationMode' : ( 'ExpirationMode_t', True, True),
    'GlueSACapability' : ( 'String', False, True),
    },
    'GlueSAPolicy' : {
        'GlueSAPolicyQuota' : ( 'Int32', True, True),
        'GlueSAPolicyMinFileSize' : ( 'Int32', True, True),
        'GlueSAPolicyMaxFileSize' : ( 'Int32', True, True),
        'GlueSAPolicyMaxData' : ( 'Int32', True, True),
        'GlueSAPolicyMaxNumFiles' : ( 'Int32', True, True),
        'GlueSAPolicyMaxPinDuration' : ( 'Int32', True, True),
        'GlueSAPolicyFileLifeTime' : ( 'String', True, True),
        },
    'GlueSAState' : { 
        'GlueSAStateUsedSpace' : ( 'Int32', True, True),
        'GlueSAStateAvailableSpace' : ( 'Int32', True, True),
},
    'GlueSEControlProtocol' : {
        'GlueSEControlProtocolLocalID' : ( 'String', True, True),
        'GlueSEControlProtocolEndpoint' : ( 'URL', True, True),
        'GlueSEControlProtocolType' : ( 'ControlProtocol_t', True, True),
        'GlueSEControlProtocolVersion' : ( 'String', True, True),
        'GlueSEControlProtocolCapability' : ( 'String', False, True),
        },
    'GlueSEAccessProtocol' : {
        'GlueSEAccessProtocolLocalID' : ( 'String', True, True),
        'GlueSEAccessProtocolEndpoint' : ( 'URL', True, True),
        'GlueSEAccessProtocolType' : ( 'AccessProtocol_t', True, True),
        'GlueSEAccessProtocolVersion' : ( 'String', True, True),
        'GlueSEAccessProtocolCapability' : ( 'String', False, True),
        'GlueSEAccessProtocolSupportedSecurity' : ( 'String', False, True),
        'GlueSEAccessProtocolPort' : ( 'Int32', True, True),
        'GlueSEAccessProtocolAccessTime' : ( 'Int32', True, True),
        'GlueSEAccessProtocolMaxStreams' : ( 'Int32', True, True),
        },
    'GlueVOView' : {
'GlueVOViewLocalID' : ( 'String', True, True),
'GlueVOViewName' : ( 'String', True, True),
'GlueVOViewPath' : ( 'String', True, True),
'GlueVOViewTag' : ( 'String', True, True),
},
}

