<?php
ini_set("include_path", "..".PATH_SEPARATOR.ini_get("include_path"));
// Call DatalibTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'DatalibTest::main');
}

require_once 'PHPUnit/Framework.php';

require_once 'Datalib.php';

/**
 * Test class for Datalib.
 * Generated by PHPUnit on 2009-09-07 at 11:57:13.
 */
class DatalibTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Datalib
     * @access protected
     */
    protected $object;

    private $file = 'test.xml';

    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main()
    {
        require_once 'PHPUnit/TextUI/TestRunner.php';

        $suite  = new PHPUnit_Framework_TestSuite('DatalibTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp() {
        copy('example.xml', $this->file);
        $this->object = new Datalib($this->file);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown() {
        unlink($this->file);
    }

    /**
     * @todo Implement testExists().
     */
    public function testExists() {
        $ip = '192.168.1.1';
        $url = 'http://test/';
        assert($this->object->exists($ip, $url)==false);
    }

    /**
     * @todo Implement testInsert().
     */
    public function testInsertDelete() {
        $ip = '192.168.1.1';
        $url = 'http://test/';
        assert($this->object->exists($ip, $url)==false);
        assert($this->object->insert($ip, $url, 'test', 'ES', 'no', 'test@cern.ch', 'true'));
        assert($this->object->exists($ip, $url)==true);
        assert($this->object->delete($ip, $url));
        assert($this->object->exists($ip, $url)==false);
    }

    /**
     * @todo Implement testUpdateStatus().
     */
    public function testUpdateStatusAndShow() {
        $ip = '192.168.1.1';
        $url = 'http://test/';
        assert($this->object->showNew()==false);
        assert($this->object->showAccepted()==false);
        assert($this->object->showDenied()==false);
        assert($this->object->insert($ip, $url, 'test', 'ES', 'no', 'test@cern.ch', 'true'));
        assert($this->object->showNew()==true);
        assert($this->object->updateStatus($ip, $url, 'accepted'));
        assert($this->object->showNew()==false);
        assert($this->object->showAccepted()==true);
        assert($this->object->updateStatus($ip, $url, 'denied'));
        assert($this->object->showAccepted()==false);
        assert($this->object->showDenied()==true);
    }
}

// Call DatalibTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'DatalibTest::main') {
    DatalibTest::main();
}
?>
