#!/bin/bash

script=../bin/gstat-validate-ce  
output=$(mktemp)

function test_ldif {
    echo -n "Testing ${ldif} ... " 
    ${script} -f $1 > ${output} 2>/dev/null
    if [ $? -eq 0 ]; then 
	echo "FAIL" 1>&2
	cat ${output}
	return
    fi
    if [ $(wc -l ${output} | sed 's/ .*//') -ne 2 ]; then
	echo "FAIL" 1>&2
	cat ${output}
	return
    fi
    grep "$2" ${output} >/dev/null 2>&1
    if [ $? -ne 0 ]; then 
	echo "FAIL" 1>&2
	cat ${output}
	return
    fi
    echo "OK"
}  

ldif=ldif/GlueSubCluster/no_ProcessorOtherDescription.ldif
message="Glue attribute GlueHostProcessorOtherDescription does not exist"
test_ldif ${ldif} "${message}"

ldif=ldif/GlueSubCluster/no_value.ldif
message="the attribute GlueHostProcessorOtherDescription does not match"
test_ldif ${ldif} "${message}"

ldif=ldif/GlueSubCluster/cores_negative.ldif
message="does not match"
test_ldif ${ldif} "${message}"

ldif=ldif/GlueSubCluster/cores_bad.ldif
message="The number of cores specified in GlueHostProcessorOtherDescription is not a valid number"
test_ldif ${ldif} "${message}"

ldif=ldif/GlueSubCluster/specint_vs_hepspec.ldif
message="The difference between the converted SI00 benchmark and HEP-SPEC06 is more than 5%"
test_ldif ${ldif} "${message}"

ldif=ldif/GlueSubCluster/cores_wrong.ldif
message="Cores \* PhysicalCPUs != LogicalCPUs"
test_ldif ${ldif} "${message}"

ldif=ldif/GlueSubCluster/physical_gt_logical.ldif
message="PhysicalCPUs should not be greater than LogicalCPUs"
test_ldif ${ldif} "${message}"

rm -f ${output}